examples/test_nmpc.c
sensitivities were mixed up and terminal cost was not passed correctly. Checked against ACADO.
=> fixed bug in test_nmpc.c

test/CMakeLists.txt
I inadvertently disabled OOQP by the CMake restructuring of the unit tests
=> activate OOQP again

acados/dense_qp/dense_qp_common.c, acados/dense_qp/dense_qp_common.h, acados/dense_qp/dense_qp_hpipm.c, acados/dense_qp/dense_qp_qore.c, acados/dense_qp/dense_qp_qpoases.c, acados/ocp_qp/ocp_qp_common.c, acados/ocp_qp/ocp_qp_common.h, acados/ocp_qp/ocp_qp_condensing_solver.c, acados/ocp_qp/ocp_qp_hpipm.c, acados/ocp_qp/ocp_qp_sparse_solver.c, acados/utils/create.c, acados/utils/print.c, acados/utils/print.h, examples/c/mass_spring_condensing_hpipm.c, examples/c/mass_spring_condensing_qore.c, examples/c/mass_spring_condensing_qpoases.c, examples/c/mass_spring_hpipm.c, examples/c/mass_spring_pcond_hpipm_split.c, examples/c/mass_spring_pcond_solver.c
example output (cond_qpoases):
***************************************************************
total time      =         0.930 ms      =        100.00 %
condensing time =         0.044 ms      =          4.74 %
QP time         =         0.875 ms      =         94.08 %
interface time  =         0.009 ms      =          1.00 %
misc            =         0.002 ms      =          0.19 %
***************************************************************
=> added cpu timings to QP solvers

.gitignore, acados/dense_qp/dense_qp_common.c, acados/dense_qp/dense_qp_common.h, acados/ocp_qp/ocp_qp_common.c, acados/ocp_qp/ocp_qp_common.h, acados/ocp_qp/ocp_qp_common_frontend.c, acados/ocp_qp/ocp_qp_common_frontend.h, examples/c/mass_spring_cond_solver.c, examples/c/mass_spring_condensing_hpipm.c, examples/c/mass_spring_condensing_hpipm_split.c, examples/c/mass_spring_condensing_qore.c, examples/c/mass_spring_condensing_qpoases.c, examples/c/mass_spring_hpipm.c, examples/c/mass_spring_pcond_hpipm_split.c, examples/c/mass_spring_pcond_solver.c
Summary of changes:
- added functions to compute inf norm of KKT residuals for dense/OCP QP
- added the computation of inf norm of residuals to the OCP QP frontend
- updated C mass spring examples to print only the inf norm of residuals
- added assert to C mass spring examples to check that the largest KKT residual is smaller than some tolerance
I used the following tolerances:
- QORE/qpOASES: ACADOS_EPS, i.e. 1e-12
- HPIPM: 1e6*ACADOS_EPS, i.e. 1e-6
=> Infinity norm of KKT residuals

cmake/FindCasadiPython.cmake
In Casadi 3.3.0, casadi.CasadiMeta_getVersion() was removed. Use `casadi.__version__` instead.
=> Fix cmake get Casadi version for Casadi 3.3.0

CMakeLists.txt, acados/dense_qp/dense_qp_qore.c, acados/utils/types.h, examples/matlab/ocp_qp_example.m, examples/python/ocp_qp.py, interfaces/acados_cpp/ocp_qp.cpp, interfaces/acados_cpp/ocp_qp.hpp, interfaces/acados_cpp/utils.hpp, swig/ocp_qp.i
It is now possible to set bounds from Python and/or MATLAB, like so
qp.set('lbx', [-inf; lb1; lb2])
qp.set('ubx', [+inf; ub1; ub2])
and so on. It is assumed that all states and constraints have bounds, they are initialized at -/+ infinity.
=> Bounds from the interfaces

CMakeLists.txt
Command [`target_sources`](https://cmake.org/cmake/help/v3.1/command/target_sources.html) is available only from cmake 3.1.
With cmake 3.0.0-rc3 I get this error:
```
-->~/build/cmake-3.0.0-rc2-Linux-i386/bin/cmake -D SWIG_MATLAB=0 -D SWIG_PYTHON=0 -D ACADOS_WITH_QORE=0 ..                                           
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Build type is Release
-- …
```
=> Bump minimum version of cmake

acados/sim/sim_lifted_irk_integrator.c
no expansion step is performed if opts->sens_adj = false, i.e. multiple shooting + lifted integrators (Newton step) != direct collocation (Newton step) @giaf @dkouzoup @FreyJo
=> add TODO (opts->sens_adj = false)

interfaces/acados_cpp/ocp_qp/ocp_qp.cpp, interfaces/acados_cpp/ocp_qp/ocp_qp.hpp, swig/acados.i, swig/conversions.i, swig/ocp_qp.i, swig/ocp_typemaps.i
It should be possible now to read out dimensions. Took a while because of the following caveats:
- SWIG is apparently not able to automatically wrap `std::map` as MATLAB structs
- to be consistent, I manually coded a conversion to Python `dict` as well
- `%template` clauses still necessary
=> Fix for #225

Makefile.rule, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp.h, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_nlp/ocp_nlp_sqp_rti.h, examples/c/Makefile, examples/c/nonlinear_chain_ocp_nlp.c, examples/c/pendulum_scqp.cpp, examples/c/pendulum_sqp_gn.cpp, examples/c/wind_turbine_nmpc.c, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_cpp/ocp_nlp/ocp_nlp.cpp, interfaces/simulink/ocp_nlp_s_function.c, test/ocp_nlp/test_chain.cpp, test/ocp_nlp/test_wind_turbine.cpp
=> add parallelization to multiple shooting

acados/sim/sim_gnsf.c, acados/sim/sim_gnsf.h, acados/sim/sim_irk_integrator.c, examples/c/sim_inverted_pendulum.c, interfaces/matlab/sim/determine_input_nonlinearity_function.m, interfaces/matlab/sim/determine_trivial_gnsf_transcription.m, interfaces/matlab/sim/generate_c_code_implicit_ode.m, interfaces/matlab/sim/reformulate_with_LOS.m, interfaces/matlab/sim/structure_detection_print_summary.m
Hey guys,
Brief overview on changes I lately did:
1. `sim_irk` fixed bug when sens_hess is used with jac_reuse
2. `sim_gnsf` modified simulation of linear output system. Before inv(M2) was stored, now LU_factorization(M2), decreasing the memory needed.
3. gnsf transcription & code generation: minor fixes, using the code generation for implicit MX Casadi models should work now.
=> Update on integrators

README.md
fixed the download paths, and added --show-progress to wget that you are able to see if the download succeeded
=> Installation instructions casadi download path fix

interfaces/acados_template/acados_template/c_templates/acados_solver.in.h
This allows the c generated files from `acados_templates` interface to be linked to cpp applications, i.e. ROS nodes.
=> templates: Fix cpp compatibility

docs/interfaces/index.md
"acados_c_shared" is not existing. The correct should be "make acados_shared".
=> Fixed make command for creating shared libraries in the documentation.

interfaces/acados_matlab/ocp_generate_casadi_ext_fun.m, interfaces/acados_matlab/sim_generate_casadi_ext_fun.m
Notes:
- ~Need to create a temporary empty file `ocp_model.c` to set the output name of the shared library to `ocp_model.so`. Renaming is not possible somehow. `mbuild` uses the first c-file to determine the output name. Any idea how to set the output name with `mbuild` or `mex`?~
- There are two possible commands using `mbuild` or `mex`. The `mbuild` command is a bit simpler thus preferred i guess, but we need to test if it works on all platforms.
=> Use mbuild to build ocp model ext fun

examples/c/CMakeLists.txt, examples/c/no_interface_examples/ocp_qp.c
this example broke with the latest update of HPIPM.
Note: the example is only fixed with an HPIPM version that merged this https://github.com/giaf/hpipm/pull/67
=> C examples: fixed ocp_qp example and moved to 'no_interface', removed  from cmake

.appveyor.yml, acados/sim/sim_gnsf.c, test/CMakeLists.txt
- Use MinGW to compile acados on appveyor
- Fix for sh.exe and PATH to MinGW in appveyor script
- Build examples on appveyor
- Run examples on appveyor
- Floating point comparison fix in sim_gnsf (by @FreyJo)
=> Running tests with appveyor, compile on appveyor with mingw

.travis.yml, ci/linux/dispatch.sh, ci/shared/after_success_package_release.sh
The after_success section in .travis.yml does not seem to be running successfully (DEPLOY_FOLDER is not defined by default). With these few changes, it should be possible to obtain GitHub Releases that include binaries and source code by simply tagging the desired commits.
=> add binaries to releases

CMakeLists.txt
On Windows mex can only link to static .lib files.
If BUILD_SHARED_LIBS is set ON then it will create .dll and .a files that are not found by the mex command,
=> CMake: default to creating shared lib on linux and static lib on windows

ROADMAP.md, acados/dense_qp/dense_qp_qpoases.c, acados/dense_qp/dense_qp_qpoases.h, acados/ocp_nlp/ocp_nlp_dynamics_cont.c, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/sim/sim_common.c, acados/sim/sim_common.h, acados/sim/sim_gnsf.c, acados/sim/sim_irk_integrator.c, acados/sim/sim_irk_integrator.h, acados/utils/math.h, examples/acados_matlab_octave/pendulum_on_cart_model/example_ocp.m, examples/acados_matlab_octave/pendulum_on_cart_model/experiment_dae_formulation.m, examples/acados_matlab_octave/pendulum_on_cart_model/pendulum_on_cart_model.m, examples/acados_matlab_octave/pendulum_on_cart_model/pendulum_on_cart_model_dae.m, examples/acados_matlab_octave/swarming/example_ocp.m, interfaces/acados_matlab_octave/acados_ocp_opts.m, interfaces/acados_matlab_octave/ocp_create.c, interfaces/acados_matlab_octave/ocp_set.c
Outdated:
<del>There was a mistake when updating the `z` variables in the `ocp_nlp_sqp_[rti]` solver.
The fix is in this commit: https://github.com/acados/acados/commit/b394ad5e53067aa1d64aeb0cc5c2be7565350d95
fixed in https://github.com/acados/acados/pull/478 instead..
=> Implement exact output of algebraic variables and corresponding sensitivities in IRK

interfaces/acados_template/acados_template/generate_solver.py
Avoid silent defaulting and implement setter for `ocp_nlp_out` `x` and `u` (for warm-start and initialization).
=> Templates quickfix: avoid silent defaulting

interfaces/acados_template/acados_template/acados_ocp_nlp.py, interfaces/acados_template/acados_template/c_templates/Makefile.in, interfaces/acados_template/acados_template/c_templates/acados_sim_solver.in.c, interfaces/acados_template/acados_template/c_templates/acados_sim_solver.in.h, interfaces/acados_template/acados_template/c_templates/main.in.c, interfaces/acados_template/acados_template/generate_solver.py
Fixing issue with shallow copy in generate_solver.py. @FreyJo @giaf I have tried to fix the same issue in MATLAB, without success :P If you figure out how to to deep copies of objects in MATLAB, we can do the same for the MEX interface too ;) 
PS: I have also fixed an inconsistency in the Jinja templates (some people still use them).
=> Quickfix template

interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
1. fix bug in acados_sover.in.c - wrong dimension for lphi_e uphi_e
2. header fix: acados_update_param -> acados_update_params
=> fix bug in acados_sover.in.c - wrong dimension for lphi_e uphi_e

interfaces/acados_template/setup.py
When using tools like `python setup.py bdist_wheel` a python package can be produced and shared with other developers.
Because of frequent changes, it is not convenient to update version in setup.py on each change. The scm module will update change accordingly to git version (using annotated tags).
=> Use setuptools-scm to simplify package building of Python acados_template

interfaces/acados_template/acados_template/c_templates_tera/acados_solver_sfun.in.c
Matlab crashes when using the generated s-function with a segfault (including when using the example getting_started - simulink_model_closed_loop).
=> s-fun templates: fix pointer. avoids segfault and matlab crash

acados/ocp_qp/ocp_qp_osqp.c
After cmake with ACADOS_WITH_OSQP=ON, during install, expected identifier error happens because osqp/include/constants.h defines MAX_ITER, and hpipm/include/hpipm_common.h has an enum with a MAX_ITER element. osqp includes need to be done after hpipm includes.
=> fix expected identifier error. happens when installing hpipm and osqp

CMakeLists.txt, acados/dense_qp/dense_qp_common.c, acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_constraints_bgh.c, acados/ocp_nlp/ocp_nlp_cost_ls.c, acados/ocp_nlp/ocp_nlp_dynamics_cont.c, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_qp/ocp_qp_common.c, acados/ocp_qp/ocp_qp_hpipm.c, acados/ocp_qp/ocp_qp_partial_condensing.c, docs/memory_management.md
Replacing #593:
I added the file:
`docs/memory_management.md`, which is intended for developers and documents how the `*_calculate_size`, `*_assign` functions should look like.
I made the `minimal_ocp_example` work on the Raspberry Pi 2 instance in the office, by adapting some of the core functions wrt the guidline file.
https://discourse.acados.org/t/convergence-failure-on-embedded-platform/122/6
Note: that for now, this does not mean that there is full acados support on 32 Bit architectures.
The next steps to do on a 32 Bit machine would be
I suggest to copy these points (and further ones from discussion) to a new issue and close related outdated issues.
For now the official statement should still be that acados does not support 32 Bit architectures.
Feedback very welcome!
=>  Memory management - some fixes wrt 32 Bit architectures

acados/CMakeLists.txt, cmake/acadosConfig.cmake.in
Only look for the external modules needed by the compiled acados installation.
=> Fix automatic acadosConfig.cmake generation

.github/linux/install_casadi_octave.sh, .github/workflows/full_build.yml
Octave template tests were failing irregularly without proper error on old Octave.
=> github actions: use ubuntu20.04, Octave 5.2.0, CasADi 3.5.5

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp.h, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_nlp/ocp_nlp_sqp_rti.h, acados/utils/external_function_generic.c, acados/utils/external_function_generic.h, interfaces/acados_matlab_octave/acados_ocp_opts.m, interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_options_json.m, interfaces/acados_matlab_octave/ocp_create.c, interfaces/acados_matlab_octave/ocp_get.c, interfaces/acados_template/acados_template/acados_layout.json, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
- parametric CasADi functions: Removed memory & avoid copying, see https://discourse.acados.org/t/solver-getting-slow-with-a-large-number-of-parameters/290/5
- globalization: add options `alpha_min, alpha_reduction`
=> parametric functions & globalization options

acados/utils/math.c
`m` was (in some cases) incremented once too much, resulting in a segmentation fault.
Found this bug with the example code from this forum post:
https://discourse.acados.org/t/matlab-crashing-on-difficult-non-linear-dynamics/329
=> fix bug in tql2, Symmetric tridiagonal QL algorithm;

interfaces/acados_template/acados_template/acados_layout.json, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_sim.py, interfaces/acados_template/acados_template/acados_sim_solver.py, interfaces/acados_template/acados_template/generate_c_code_constraint.py, interfaces/acados_template/acados_template/generate_c_code_discrete_dynamics.py, interfaces/acados_template/acados_template/generate_c_code_explicit_ode.py, interfaces/acados_template/acados_template/generate_c_code_external_cost.py, interfaces/acados_template/acados_template/generate_c_code_gnsf.py, interfaces/acados_template/acados_template/generate_c_code_implicit_ode.py, interfaces/acados_template/acados_template/generate_c_code_nls_cost.py
The code export directory can be set in AcadosOcp.code_export_directory and
AcadosSim.code_export_directory.
The constructor of AcadosSimSolver transfers the setting from AcadosOcp to
AcadosSim if initialized with an AcadosOcp object.
=> acados_template: configurable code export directory

acados/utils/timing.c, acados/utils/timing.h, examples/acados_python/getting_started/sim/minimal_example_sim.py, interfaces/acados_c/sim_interface.c, interfaces/acados_c/sim_interface.h, interfaces/acados_template/acados_template/acados_sim_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver_sfun.in.c, interfaces/acados_template/acados_template/c_templates_tera/main_sim.in.c
- Introduced capsule to avoid global memory
- according changes in S Function & main_sim
- dimension check
- improved acados timings on minGW, see https://discourse.acados.org/t/resolution-of-internal-timers-used-for-returning-solution-timings/396/4 thanks to @Hespe
=> Python integrator interface improvements

interfaces/acados_template/acados_template/utils.py
Since `ACADOS_SOURCE_DIR` is current only used to find the tera path, we could remove it, but not sure if it's wanted for future use.
=> acados_template: make tera path configurable

interfaces/acados_matlab_octave/acados_sim.m
Hello everyone,
in "acados_sim.m", the code was looking for a file with extension "mexa64" to check whether compilation is necessary, but on windows the extension name should be "mexw64". The Matlab function "mexext" returns the correct extension.
=> acados_sim, option "compile_interface": Fixed value "auto" not working correctly on windows

acados/sim/sim_collocation_utils.c, acados/sim/sim_collocation_utils.h, acados/sim/sim_common.c, acados/sim/sim_common.h, acados/sim/sim_erk_integrator.c, acados/sim/sim_gnsf.c, acados/sim/sim_irk_integrator.c, acados/sim/sim_lifted_irk_integrator.c, examples/acados_matlab_octave/test/test_template_pendulum_ocp.m, examples/acados_python/getting_started/sim/minimal_example_sim.py, interfaces/acados_c/sim_interface.h, interfaces/acados_matlab_octave/acados_ocp_opts.m, interfaces/acados_matlab_octave/acados_sim_opts.m, interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_options_json.m, interfaces/acados_matlab_octave/ocp_create.c, interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m, interfaces/acados_matlab_octave/sim_create.c, interfaces/acados_template/acados_template/acados_layout.json, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_sim.py, interfaces/acados_template/acados_template/acados_sim_layout.json, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
- supports `GAUSS_LEGENDRE` and `GAUSS_RADAU_IIA` to use corresponding Butcher tableaus in implicit integrators
- clean up collocation utils
=> Add collocation_type option

examples/acados_python/getting_started/common/utils.py, examples/acados_python/getting_started/ocp/minimal_example_ocp_reuse_code.py, interfaces/CMakeLists.txt, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/main.in.c, interfaces/acados_template/acados_template/c_templates_tera/main_sim.in.c
This PR adds some improvements to the exported code
1. help to identify constant time-steps with numerical differences (improves reliability when distinguishing code paths in template)
2. ocp & main: help reuse exported code, since the model is independent of the number of shooting nodes
3. sim & main: use dimension defines and help with code readability (use parameters instead of numbers in code)
4. example minimal_example_ocp_reuse_code.py added to ctest
=> acados_template improvements

interfaces/acados_template/acados_template/c_templates_tera/Makefile.in
Some useful patterns and implicit rules from
http://www.gnu.org/software/make/manual/make.html
are applied here.
The explicit definition of all objects files is replaced by make's implicit rules.
This makes the resulting Makefile also more human readable.
=> templates: simplify Makefile.in with implicit rules and patterns

acados/ocp_nlp/ocp_nlp_common.c, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_sim_solver.py
This PR should fix issues #777 and #782.
Explanation: both issues seem to have the same root cause, since `libacados.so` is loaded by the solver. Upon destruction of the solver it seems that also `libacados.so` is unloaded and that causes the issues.
- In #777 `qpDUNES` seems to close `stdout` during destruction.
- In #782 the threads created by `OpenMP` are spin waiting in the background and cause a segmentation fault.
The solution is to load `libacados.so` separately and avoid unloading upon destruction of the solver.
This PR also allows the two tests `main_test.py` (external call to python) and `armijo_test.py` (multiple creations/destructions of solvers in the same python session) under `examples/acados_python/tests` to run correctly.
=> Fix OpenMP segfault and qpDUNES print issue

examples/acados_python/getting_started/ocp/minimal_example_ocp_reuse_code.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
The goal:
1) Split the long function *_acados_create_with_dicretization() into several (numbered) sub-functions to give it some structure.
2) That also facilitates to set "qp_cond_N" afterwards using new function {{ model.name }}_acados_update_qp_solver_cond_N(...). This also allows for better code reuse after code export.
3) Macro MAP_CASADI_FNC to simplify the CasADi function mapping.
=> Templates: simplify acados_solver.in.c and code reuse

interfaces/acados_matlab_octave/acados_ocp_opts.m, interfaces/acados_matlab_octave/acados_sim_opts.m, interfaces/acados_matlab_octave/ocp_generate_casadi_ext_fun.m, interfaces/acados_matlab_octave/sim_generate_casadi_ext_fun.m
this allows to reduce code optimizations conveniently, which is needed for big models
=> Matlab: add option ext_fun_compile_flags with default `-O2`

interfaces/acados_matlab_octave/acados_ocp_opts.m, interfaces/acados_template/acados_template/acados_ocp.py
The square-root version is supposed to be faster, and also better conditioning wise, since the square-root values are closer to 1.
At the last release: The default in C and Python was 1. The default in Matlab was 0.
In 751a8000c1e980c4e312a83cb4c90102bee49e9c I had added support for those options in Python with default as in Matlab.
=> Change defaults of qp_solver_ric_alg, qp_solver_cond_ric_alg to 1, i.e. square-root version

CMakeLists.txt, acados/ocp_nlp/ocp_nlp_sqp.c
This writes all QP inputs and outputs of the latest SQP call into files called
`qp_in_{{iterate_number}}.txt`,  `qp_out_{{iterate_number}}.txt` in the current working directory.
Previous files with the same name are overwritten.
Could be extended to not overwrite, but should be compatible with Windows, see https://stackoverflow.com/questions/230062/whats-the-best-way-to-check-if-a-file-exists-in-c
=> add flag: ACADOS_DEBUG_SQP_PRINT_QPS_TO_FILE

interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/utils.py
Changes:
- The exception messages in the get(stage, field) now contain the stage number.
- Conversion from most sting.format(...) to f-strings.
- Add small exception readability improvements (add more of the quotation marks, e.g., around 'field').
=> Python: OCP solver: exception messages with stage number and f-strings

examples/acados_matlab_octave/getting_started/extensive_example_ocp.m, examples/acados_matlab_octave/pendulum_on_cart_model/example_ocp_reg.m, examples/acados_python/getting_started/ocp/example_sqp_rti_loop.py, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_matlab_octave/ocp_get.c, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx, interfaces/acados_template/acados_template/acados_solver_common.pxd
Two breaking changes, of not widely used functionality:
Python / C:
[BREAKING: rename dynamics_get -> get_from_qp_in](https://github.com/acados/acados/commit/41a599971a9ec96e1cf02ade3b6f61507be548b4)
Matlab:
[BREAKING: Matlab: change 'qp_solver_A' to 'qp_A'](https://github.com/acados/acados/commit/1c4256f152657b40dc7fc13e66d79e40ca06ada4)
=> Add possibility to get QP matrices from Matlab and Python interfaces

interfaces/acados_matlab_octave/detect_constr.m
parametric constraints should be casadi functions
Reported in https://discourse.acados.org/t/product-of-parameters-and-an-optimization-variable-in-constraints-leads-to-error/842
=> Matlab: fix constraint detection

interfaces/acados_matlab_octave/detect_cost_type.m
Hey guys! I found a small bug in the MATLAB interface - here is a quick fix.
=> Matlab: fix algebraic variables offset in detect_cost_type.m

interfaces/acados_template/acados_template/acados_ocp_solver.py
bug reported in
https://discourse.acados.org/t/trying-to-set-0-parameters-for-external-functions-external-function-has-42-parameters/860
=> fix: param set in python, np was missing in ctypes signature

acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_nlp/ocp_nlp_sqp_rti.h
- make feedback and preparation phase functions private
- avoid casting workspace and others multiple times for performance and less code duplication
=> Simplify SQP_RTI

acados/sim/sim_irk_integrator.c, acados/sim/sim_lifted_irk_integrator.c
Before this fix, the example `nonuniform_discretization_example.py` failed with:
```
Unknown external function argument type for argument 3
```
Bug wasn't showing before, probably due to older compiler.
=> Fix lifted IRK with empty z input; formatting

acados/dense_qp/dense_qp_daqp.c
If the problem setup fails (for example due to trivial infeasibility or nonconvex hessian), abort the qp solve.
=> DAQP: Abort solve if setup fails

interfaces/acados_matlab_octave/ocp_generate_casadi_ext_fun.m, interfaces/acados_matlab_octave/sim_generate_casadi_ext_fun.m
When generating a Simulink s-function a number of c-files are compiled using the mex compilation setup and these are linked with a library containing the casadi_ext_fun. The compilation of this library does not use mex compilation, but is rather a system call directly to the compiler. For this to work it is required that the compiler used by mex is added to the OS PATH environment variable.
As we need to have another (incompatible) version of gcc in our OS PATH environment variable acados will use this incompatible gcc version to compile the cadasdi_ext_fun library and the linking will subsequently fail.
=> Matlab remove os path dependency

docs/installation/index.md, interfaces/acados_matlab_octave/acados_env_variables_windows.m, interfaces/acados_matlab_octave/acados_install.m, interfaces/acados_matlab_octave/acados_install_windows.m, interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/render_acados_templates.m, interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/set_up_t_renderer.m, interfaces/acados_matlab_octave/check_acados_requirements.m, interfaces/acados_matlab_octave/ocp_compile_interface.m, interfaces/acados_matlab_octave/ocp_set_ext_fun.m, interfaces/acados_matlab_octave/sim_set_ext_fun.m
Install script for automating acados installation using Matlab.
Also includes minor changes to enable full installation without user interaction.
Note: A few files were moved from examples to interfaces as they are actually needed to use acados and are thus part of the interface and not an example.
Furthermore, the include directory references were changes to point at the include directory created automatically when installing acados instead of directly from the source. This enables management of the acados install used on an enterprise level where the responsible software engineer can generate an acados package with a specific configuration and share a minimal and compiled acados distribution to the engineers using the solver generation.
=> Automate matlab install

acados/ocp_nlp/Makefile
fix: Makefile for conl cost
reported here: https://discourse.acados.org/t/conl-cost-not-in-makefile/978/2
=> fix: Makefile for conl cost

docs/python_interface/index.md
The link to the discourse page is relative but needs to be absolute.
Clicking the `acados forum` link on https://docs.acados.org/python_interface/index.html# will lead to `https://docs.acados.org/python_interface/discourse.acados.org/` instead of `https://discourse.acados.org/`
=> docs: fix broken discourse link in documentation

examples/acados_python/pendulum_on_cart/ocp/nonuniform_discretization_example.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_sim_solver.py, interfaces/acados_template/acados_template/builders.py
This PR answers my own question on the [discourse forum](https://discourse.acados.org/t/disabling-compilation-stdout-output/1019?u=tudoroancea).
It simply adds a verbose argument to some of the functions of the Python interface to disable the compiler output. 
I achieved this by replacing the calls to `os.system()` by calls to `subprocess.call()` which can properly redirect the output to `/dev/null` as indicated in this [StackOverflow answer](https://stackoverflow.com/a/5597017).
I have added this option for the `CMakeBuilder` and `AcadosSimSolver` classes as well, but I may still have missed some parts of the code to change for consistency, please let me know.
=> added verbose option to AcadosOcpSolver build

acados/ocp_nlp/ocp_nlp_cost_nls.c
Hi @FreyJo 
I recently switched from a `LINEAR_LS` to a `NONLINEAR_LS` cost module in my problem formulation. I realized that the cost
matrices were not properly updated when I set them online. It appears that there was a minor mistake in #878, i.e., the `W_changed` flag is only set to true for the linear least squares module: https://github.com/acados/acados/blob/master/acados/ocp_nlp/ocp_nlp_cost_ls.c#L301
Cheers and kind regards from Freiburg ✌🏻
=> NLS cost module: Change W_changed flag if cost matrix was changed

.github/workflows/full_build.yml, acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_constraints_bgh.c, acados/ocp_nlp/ocp_nlp_constraints_bgh.h, acados/ocp_nlp/ocp_nlp_constraints_bgp.c, acados/ocp_nlp/ocp_nlp_constraints_bgp.h, acados/ocp_nlp/ocp_nlp_constraints_common.h, acados/ocp_nlp/ocp_nlp_sqp_rti.c, interfaces/acados_matlab_octave/acados_ocp.m, interfaces/acados_template/acados_template/custom_update_templates/custom_update_function_zoro_template.in.c
- Constraint modules: add `update_qp_vectors` instead of `bounds_update`
- Fix potential memory issues in BGP
- This fixes the zoRO implementation: Backoffs were delayed by 1 iteration. Backoffs are nonzero now in first iteration
=> Core: Allow changing all constraint bounds between preparation and feedback phase

examples/acados_python/chain_mass/run_nominal_control.py, examples/acados_python/getting_started/minimal_example_closed_loop.py, examples/acados_python/linear_mass_model/linear_mass_test_problem.py, examples/acados_python/non_ocp_nlp/marathos_test_problem.py, examples/acados_python/rsm_example/main.py, examples/acados_python/tests/armijo_test.py, examples/acados_python/zoRO_example/diff_drive/diff_drive_zoro_mpc.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx, interfaces/acados_template/acados_template/acados_sim_solver.py
- Get statistics with their correct types in both python and cython interface - avoid creation of 1-dim numpy array
- Make cython interface working with custom path of the `code_export_directory`
For Release notes:
- BREAKING: change return types of `get_stats` in Python
=> Python get_stats returns float or int instead of single element numpy array and fix cython for custom path

examples/acados_python/getting_started/minimal_example_sim.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_sim_solver.py, interfaces/acados_template/acados_template/builders.py, interfaces/acados_template/acados_template/utils.py
Pursuing the efforts of PR #928, I refactored all the system calls in the python interface by introducing the following utility function:
```python
def verbose_system_call(cmd, verbose=True):
return call(
cmd,
stdout=None if verbose else DEVNULL,
stderr=None if verbose else STDOUT
)
```
=> refactored optionally verbose system calls in python interface

examples/acados_python/getting_started/minimal_example_closed_loop.py
The median computation time was accidentally coded as `np.min`.
=> Fix typo in minimal_example_closed_loop.py

cmake/acadosConfig.cmake.in
This PR addresses 3 issues when consuming acados as a CMake dependency from a downstream project. 
1. Currently `find_package(acados)` breaks all following `find_package` calls since `acadosConfig.cmake` adjusts the `CMAKE_MODULE_PATH`. This should be restored to the original state per [this cmake dev](https://discourse.cmake.org/t/install-findpackage-script/5307/2) in [the manner shown here](https://discourse.cmake.org/t/cant-export-top-level-lib-with-dependency-on-subdir-lib/1084/21).
2. `add_library(gfortran)`  and `add_library(openblas)` triggers *target with the same name already exists* errors if the acados config file is processed twice, so they should be [guarded against double `add_library` by if guards](https://github.com/microsoft/vcpkg/issues/24367#issuecomment-1107798861)
3. …
=> Fix dependency handling in CMake config file

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_cost_conl.c, acados/ocp_nlp/ocp_nlp_cost_conl.h, acados/ocp_nlp/ocp_nlp_cost_nls.c, acados/sim/sim_common.c, acados/sim/sim_common.h, acados/sim/sim_irk_integrator.c, acados/sim/sim_irk_integrator.h, acados/utils/types.h, examples/acados_python/pendulum_on_cart/ocp/ocp_example_cost_formulations.py, examples/acados_python/tests/test_cost_integration_euler.py, examples/acados_python/tests/test_cost_integration_value.py, examples/acados_python/tests/test_ggn_cost_integration.py, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
-  Allows for Generalized GNRK integrator (GGNRK), eXtended GNRK integrator (XGNRK)
=> Implement cost integration via IRK for Convex-over-nonlinear cost 

docs/matlab_octave_interface/index.md, examples/acados_python/time_varying/piecewiese_polynomial_control_example.py, examples/acados_python/time_varying/test_polynomial_controls_and_penalties.py, interfaces/CMakeLists.txt, interfaces/acados_template/acados_template/__init__.py, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/penalty_utils.py
Added functions to `AcadosOcp`:
- `formulate_constraint_as_L2_penalty`
- `formulate_constraint_as_Huber_penalty`
- `translate_nls_cost_to_conl`
Added `test_polynomial_controls_and_penalties`
=> Formulate constraints as L2 and Huber penalties in Python

examples/acados_matlab_octave/pendulum_dae/pendulum_dae_model.m, examples/acados_matlab_octave/simple_dae_model/simple_dae_model.m, interfaces/acados_matlab_octave/check_casadi_version.m, interfaces/acados_matlab_octave/dump_gnsf_functions.m, interfaces/acados_matlab_octave/generate_c_code_disc_dyn.m, interfaces/acados_matlab_octave/generate_c_code_explicit_ode.m, interfaces/acados_matlab_octave/generate_c_code_ext_cost.m, interfaces/acados_matlab_octave/generate_c_code_gnsf.m, interfaces/acados_matlab_octave/generate_c_code_implicit_ode.m, interfaces/acados_matlab_octave/generate_c_code_nonlinear_constr.m, interfaces/acados_matlab_octave/generate_c_code_nonlinear_least_squares.m, interfaces/acados_matlab_octave/gnsf/determine_trivial_gnsf_transcription.m
Following https://github.com/acados/acados/issues/981
- Tested 3.6 on some examples locally
- Only raise Warning on untested CasADi versions
=> Rework CasADi requirements in MEX interface

interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
* fix bug in Python interface detecting ns_0, reported in https://discourse.acados.org/t/possible-bug-in-python-interface-slack-dimensions/1335
* fix buffer size with NS0
* fix: ns_0 in template
* remove redundant print
=> Fix bugs with slack dimensions Python interface

examples/acados_python/mocp_transition_example/main.py, examples/acados_python/pendulum_on_cart/ocp/ocp_example_cost_formulations.py, interfaces/acados_template/acados_template/acados_multiphase_ocp.py, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/multi_Makefile.in, interfaces/acados_template/acados_template/casadi_function_generation.py
This is a follow up of https://github.com/acados/acados/pull/1004 removing the limitations described therein.
An `ocp` instance of the class  `AcadosMultiphaseOcp`, now has the additional field `mocp_opts`.
This field is of the class  `AcadosMultiphaseOptions`, "containing options that might be different for each phase", namely `integrator_type`, `collocation_type`, `cost_discretization`.
All of these fields can be either `None`, then the corresponding value from `ocp.solver_options` is used, or a list of length `n_phases` describing the value for this option at each phase.
This especially allows one to define OCPs with varying state dimensions which can be formulated using a transition stage which uses discrete dynamics to map the state representation of one phase to the next phase.
An …
=> extend AcadosMultiphaseOcp

interfaces/acados_matlab_octave/acados_ocp.m, interfaces/acados_matlab_octave/acados_ocp_model.m, interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/make_sfun_sim.in.m
Support slack penalties for initial stage in MEX interface.
Follow-up on https://discourse.acados.org/t/issue-in-setting-slack-variable-on-control-input/1456
The convention is as follows now:
- bounds on u and general linear constraints are also enforced on the initial node
- bounds on x and nonlinear constraints are fully split and have to be explicitly stated with `_0` correspondence to be enforced on the stage.
=> Support slack penalties for initial stage in MEX interface

acados/ocp_nlp/ocp_nlp_dynamics_cont.c, acados/ocp_nlp/ocp_nlp_reg_common.h, acados/ocp_nlp/ocp_nlp_reg_convexify.c, acados/ocp_nlp/ocp_nlp_reg_mirror.c, acados/ocp_nlp/ocp_nlp_reg_noreg.c, acados/ocp_nlp/ocp_nlp_reg_project.c, acados/ocp_nlp/ocp_nlp_reg_project_reduc_hess.c, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_qp/ocp_qp_common.h, acados/ocp_qp/ocp_qp_full_condensing.c, acados/ocp_qp/ocp_qp_full_condensing.h, acados/ocp_qp/ocp_qp_partial_condensing.c, acados/ocp_qp/ocp_qp_partial_condensing.h, acados/ocp_qp/ocp_qp_xcond_solver.c, acados/ocp_qp/ocp_qp_xcond_solver.h, docs/algorithm_overview/index.md, examples/acados_python/pendulum_on_cart/ocp/example_sqp_rti_loop.py, examples/c/regularization.c
Condensing modules now provide
- `condense` - all condensing operations
- `condense_rhs` - condensing the right hand side
- `condense_lhs` - condensing the left hand side
Similarly, regularization modules now provide
- `regularize` - all operations
- `regularize_rhs` - operations on the right hand side
- `regularize_lhs` - operations on the left hand side
Only if RTI is split into preparation and feedback, the `_rhs` / `_lhs` routines are called.
Otherwise, operations are done all together.
Addresses https://github.com/acados/acados/issues/1031
NOTE: using convexify with split RTI phase has now relatively overhead, see https://github.com/acados/acados/issues/1035
Splitting the computations for `convexify` more efficiently should be done in another PR.
=> Split condensing and regularization into preparation and feedback

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_constraints_bgh.c, acados/ocp_nlp/ocp_nlp_dynamics_cont.c, acados/ocp_nlp/ocp_nlp_dynamics_cont.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_qp/ocp_qp_xcond_solver.c, acados/sim/sim_common.c, acados/sim/sim_common.h, acados/sim/sim_erk_integrator.c, acados/sim/sim_erk_integrator.h, acados/utils/external_function_generic.c, acados/utils/external_function_generic.h, examples/c/simple_dae_example.c, test/ocp_nlp/test_chain.cpp
- **Cast highest level workspace (SQP/SQP-RTI) only in precompute for more speed**:
This still allows to reuse workspace across modules. This can only break if one tries to reuse the acados workspace memory from outside.
- **Add CasADi sparsity detection** that is called when creating an external function.
The CasADi sparsity struct in the generated functions contains an `int` which always say inputs are sparse, often this is not the case. Thus, we check now for speed!
- Added `sim_in_assign_and_advance`, this can be called to avoid calling `calculate_size` twice. Doing this everywhere is rather tedious and does not save very much.
- **Breaking**: precompute is now required!
On a small benchmark of an RTI with ERK and the cartpole this gives me >20% speedup, from 78μs to 62μs.
=> Work on core for speedups

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_dynamics_cont.c, acados/ocp_nlp/ocp_nlp_dynamics_cont.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_nlp/ocp_nlp_sqp_rti.h, acados/ocp_qp/ocp_qp_partial_condensing.c, docs/algorithm_overview/index.md, interfaces/acados_c/ocp_nlp_interface.c
- fix timings for RTI: subtimers `time_qp*`, `time_reg` now start at 0 when starting preparation and count operations in both phases
- cleanup comments
- make enum for RTI phase
- precompute integrator workspace_size
=> Cleanup RTI, fix timings and comments

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_constraints_bgh.c, acados/ocp_nlp/ocp_nlp_constraints_bgh.h, acados/ocp_nlp/ocp_nlp_constraints_bgp.c, acados/ocp_nlp/ocp_nlp_constraints_bgp.h, acados/ocp_nlp/ocp_nlp_constraints_common.h, acados/ocp_nlp/ocp_nlp_cost_common.h, acados/ocp_nlp/ocp_nlp_cost_conl.c, acados/ocp_nlp/ocp_nlp_cost_conl.h, acados/ocp_nlp/ocp_nlp_cost_external.c, acados/ocp_nlp/ocp_nlp_cost_external.h, acados/ocp_nlp/ocp_nlp_cost_ls.c, acados/ocp_nlp/ocp_nlp_cost_ls.h, acados/ocp_nlp/ocp_nlp_cost_nls.c, acados/ocp_nlp/ocp_nlp_cost_nls.h, acados/ocp_nlp/ocp_nlp_dynamics_common.h, acados/ocp_nlp/ocp_nlp_dynamics_cont.c, acados/ocp_nlp/ocp_nlp_dynamics_cont.h, acados/ocp_nlp/ocp_nlp_dynamics_disc.c, acados/ocp_nlp/ocp_nlp_dynamics_disc.h, examples/acados_python/linear_mass_model/linear_mass_test_problem.py
In some places `tmp_ux` and `ux` where used in a mixed way, i.e. `compute_fun` of constraint modules and what was fixed in #1039 
- fixes bug when using globalization and cost computation
- fixes bug in globalization with slacks. Constraint was evaluated with slack values from SQP iterate instead of values from the line search candidate
Implementation:
- Removed all `tmp_*` pointers in SQP submodules
- Always evaluate at `ux`
- When one wants to evaluate at another iterate, these pointers have to be temporarily set to another iterate and afterwards reset to the nominal SQP iterate, as done in `ocp_nlp_evaluate_merit_fun` now.
=> Cleanup SQP submodules - only use single evaluation point at a time

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_constraints_bgh.c, acados/ocp_nlp/ocp_nlp_cost_common.h, acados/ocp_nlp/ocp_nlp_cost_conl.c, acados/ocp_nlp/ocp_nlp_cost_external.c, acados/ocp_nlp/ocp_nlp_cost_external.h, acados/ocp_nlp/ocp_nlp_cost_ls.c, acados/ocp_nlp/ocp_nlp_cost_nls.c, acados/ocp_nlp/ocp_nlp_dynamics_common.h, acados/ocp_nlp/ocp_nlp_dynamics_cont.c, acados/ocp_nlp/ocp_nlp_dynamics_cont.h, acados/ocp_nlp/ocp_nlp_dynamics_disc.c, acados/ocp_nlp/ocp_nlp_sqp.h, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_nlp/ocp_nlp_sqp_rti.h, acados/sim/sim_erk_integrator.c, examples/acados_python/pendulum_on_cart/as_rti/as_rti_closed_loop_example.py, examples/acados_python/pendulum_on_cart/common/utils.py, examples/c/no_interface_examples/mass_spring_example.c, examples/c/sim_gnsf_crane.c, interfaces/CMakeLists.txt, interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_options_json.m, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
This pull request implements the advanced-step real-time iteration (AS-RTI)
It is implemented as a feature within the `RTI` module.
In order to use it, set the new options:
- `as_rti_level`
- `as_rti_iter`
The feedback phase of RTI and AS-RTI is the same.
The AS-RTI preparation phase is used instead of the "standard" RTI preparation phase, when the options above are set.
Additionally, this adds the flag:
- `rti_log_residuals`: which allows to log the residuals within (AS-)RTI. This was needed for the experiment in the paper, which reports the residuals of the inner iterations. Limited to convex-over-nonlinear and external cost modules for now.
The work in this PR is presented in the publication
"Advanced-Step Real-time Iterations with Four Levels -- New Error Bounds and Fast …
=> Implement advanced-step real-time iteration: AS-RTI

interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/acados_ocp_layout.json
This was missing in https://github.com/acados/acados/pull/1059 to make this work in matlab for nsh_0 > 0.
https://github.com/acados/acados/issues/1056
=> add idxsh_0 to layout

interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/make_sfun.in.m, interfaces/acados_template/acados_template/simulink_default_opts.json
Added an output port in the acados_ocp S-function block for the algebraic states' trajectory, `ztraj`, equivalent to `xtraj`.
=> Matlab Interface: Add ztraj to sfunction output

interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/make_sfun.in.m, interfaces/acados_template/acados_template/simulink_default_opts.json
allows to split the computations of an OCP solve into preparation and feedback phase.
=> Add `rti_phase` as possible Simulink input

cmake/acadosConfig.cmake.in
Adjusting CMAKE_PREFIX_PATH in acadosConfig.cmake breaks dependency handling by catkin when building a ROS package that depends on acados.
ROS's buildtool `catkin` controls `CMAKE_PREFIX_PATH` in the environment to [handle "workspaces"](https://catkin-tools.readthedocs.io/en/latest/verbs/catkin_config.html#explicitly-specifying-workspace-chaining), which collides with `acadosConfig.cmake`'s own path adjustments.
Instead of replicating  #971's means of reverting path adjustment at exit, I simply deleted the path adjustment command as it seems to serve no purpose. The associated comment suggests an absurd thing - no `*Config.cmake` files could exist in the parent of the `cmake` folder, which could either be root `acados` in case of default install or `/usr/local` in case of global install
=> Remove local `CMAKE_PREFIX_PATH` adjustments

cmake/acadosConfig.cmake.in
This reverts commit 3594673f36022ab7d57f58014d83509c0b76d7fd.
After two people experienced failing builds with ROS2 after #1083 let's revert this change.
See https://github.com/acados/acados/commit/3594673f36022ab7d57f58014d83509c0b76d7fd
=> Revert "Remove local `CMAKE_PREFIX_PATH` adjustments (#1083)"

examples/acados_python/pendulum_on_cart/ocp/minimal_example_batch_ocp_solver.py, examples/acados_python/pendulum_on_cart/sim/minimal_example_batch_sim_solver.py, interfaces/CMakeLists.txt, interfaces/acados_template/acados_template/acados_ocp_batch_solver.py, interfaces/acados_template/acados_template/acados_sim_batch_solver.py
Apparently, shared libraries with and without openmp cannot easily be combined.  If the acados batch solvers introduced in #1087  should be used, it is thus recommended to compile the acados shared library with openmp and set the number of threads to 1.
This problem seems to be related to:
* https://github.com/JuliaLang/julia/issues/10938
* https://github.com/casadi/casadi/issues/2447
This PR implements corresponding warnings in `AcadosOcpBatchSolver` and `AcadosSimBatchSolver` and removes the examples from the tests (as we do not want to compile acados with openmp for all tests).
=> Follow up to #1087

interfaces/acados_matlab_octave/check_acados_requirements.m, interfaces/acados_matlab_octave/check_casadi_version.m, interfaces/acados_matlab_octave/detect_gnsf_structure.m
Managed to run some examples with Octave 6.4.0 and CasADi 3.6.5, see https://github.com/acados/acados/issues/992
Made some small changes to the CasADi automatic download / instructions.
=> Octave works

interfaces/acados_matlab_octave/detect_cost_type.m
Newer casadi versions do not allow free variables when creating casadi functions.
=> Fix cost type detection for casadi versions >= 3.6

acados/dense_qp/dense_qp_common.h, acados/dense_qp/dense_qp_daqp.c, acados/dense_qp/dense_qp_hpipm.c, acados/dense_qp/dense_qp_ooqp.c, acados/dense_qp/dense_qp_qore.c, acados/dense_qp/dense_qp_qpoases.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_qp/ocp_qp_common.h, acados/ocp_qp/ocp_qp_hpipm.c, acados/ocp_qp/ocp_qp_hpmpc.c, acados/ocp_qp/ocp_qp_ooqp.c, acados/ocp_qp/ocp_qp_osqp.c, acados/ocp_qp/ocp_qp_qpdunes.c, acados/ocp_qp/ocp_qp_xcond_solver.c, acados/ocp_qp/ocp_qp_xcond_solver.h, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h
Add functionality in `ocp_nlp_solver_destroy` to allow freeing memory in submodules, such as external QP solvers.
Fix OSQP memory leak by adding: `qp_solver->terminate`.
=> Add functionality in `ocp_nlp_solver_destroy`

interfaces/acados_template/acados_template/acados_ocp.py
This adds a call to `model.make_consisten` before reformulating as feasibility problem.
=> Fix reformulation to feasibility problem for empty symbolics

examples/acados_python/unconstrained_ocps/chen_allgoewer_unconstrained_ocp/chen_allgoewer_ocp.py, examples/acados_python/unconstrained_ocps/chen_allgoewer_unconstrained_ocp/chen_allgoewer_system_model.py, interfaces/acados_template/acados_template/acados_model.py, interfaces/acados_template/acados_template/acados_ocp.py
Handle the initial state constraint in `translate_to_feasibility_problem` in 3 different ways:
- 1. (default): bake in x0 constraint as part of the penalty formulation
- 2. `keep_x0`: initial state constraint is formulated as upper and lower bound on x at 0 (standard in acados), values can be updated as for standard problems
- 3. replace the value of the initial state constraint with a parameter that is appended to the model parameters. Initial state constraint can then be updated by setting the parameter.
Example update:
- The Chen Allgoewer problem tests two problems now. One problem has a changed x0 parameter
- In the Chen Allgoewer model you can choose if you want SX or MX variables
=> Feasibility Problem Reformulation enhancement

examples/acados_python/tests/reset_test.py, examples/acados_python/timing_example/reset_timing.py, interfaces/acados_template/acados_template/acados_ocp_solver.py
Allow to set `max_iter` in Python.
Check whether the value requested is higher than the one used to allocate memory and raise an Exception in this case.
Minor changes:
- Make `solver_options` of `AcadosOcpSolver` private
- `np.NaN` -> `np.nan`
=> Setter for updating `max_iter` in Python

interfaces/acados_template/acados_template/c_templates_tera/CMakeLists.in.txt, interfaces/acados_template/acados_template/c_templates_tera/Makefile.in, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/constraints.in.h, interfaces/acados_template/acados_template/c_templates_tera/multi_Makefile.in, interfaces/acados_template/acados_template/casadi_function_generation.py
The function `nl_constr_phi_o_r_fun` which is used in `ocp_nlp_constraints_bgp_compute_fun` hasn't been generated and set in the templates.
This PR adds the additional external function, `phi_constraint_fun`,  and renames the existing one from `phi_constraint` to `phi_constraint_fun_jac_hess` within the templates.
TODO: Test multi-phase solver with CONL constraints and globalization
=> Add missing external function for convex-over-nonlinear constraints

acados/utils/timing.c, acados/utils/timing.h
This PR implements the fix suggested [here](https://discourse.acados.org/t/error-during-runing-the-example-in-matlab-2019b/1579/6).
Now the native Windows timing functionality is used also when compiling with MinGW.
This was tested on two machines (one had the original issue) and it works in both cases.
The difference in timing when running the `linear_mpc` example is ca. 0.002 ms (0.178 ms total solve time).
=> Windows, MATLAB - Fix timing with MinGW

examples/acados_python/pendulum_on_cart/ocp/nonuniform_discretization_example.py, examples/acados_python/pendulum_on_cart/ocp/simulink_example.py, examples/acados_python/zoRO_example/pendulum_on_cart/minimal_example_zoro.py, interfaces/acados_template/acados_template/acados_ocp_constraints.py, interfaces/acados_template/acados_template/utils.py
- deprecate `get_default_simulink_opts`, use `get_simulink_default_opts` instead
- return `x0` if set
=> Python cleanup

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_ddp.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp.h, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/utils/print.c, examples/acados_matlab_octave/getting_started/extensive_example_ocp.m, examples/acados_matlab_octave/test/test_ocp_wtnx6.m, examples/acados_python/linear_mass_model/linear_mass_test_problem.py, examples/acados_python/non_ocp_nlp/marathos_test_problem.py, examples/acados_python/pendulum_on_cart/ocp/nonuniform_discretization_example.py, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/acados_ocp_layout.json, interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_options_json.m, interfaces/acados_matlab_octave/ocp_get.c, interfaces/acados_template/acados_template/acados_model.py, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/mex_solver.in.m
The slacks `t` that were used to slack the inequality constraint values are actually not needed in an NLP solver and are thus removed in this PR.
Instead of using `t`, we now directly evaluate inequality residual using the function evaluations.
This results in consistent inequality residuals and will help future work on globalization.
Related interface functionality such as getters and setters for `t` and `initialize_t_slacks` have been removed.
=> Remove `t` slacks from `ocp_nlp_out`

Makefile
Hi, I noticed two small typos in the Makefile.
Also, I was wondering if something similar to [this section](https://github.com/acados/acados/blob/master/Makefile#L71-L73) should be added for [DAQP](https://github.com/acados/acados/blob/master/acados/dense_qp/dense_qp_daqp.c)?
EDIT: I see now that DAQP is not included in the Makefile, not sure if it's relevant in that case.
=> Fix small typo in Makefile

interfaces/acados_template/acados_template/acados_sim.py
BREAKING: change default for `sim_method_num_stages` to 4 in `AcadosSim` to be consistent with the default in `AcadosOcp`
=> Python interface: default for `sim_method_num_stages`

acados/utils/external_function_generic.c, examples/acados_python/pendulum_on_cart/sim/sparse_param_test.py, examples/acados_python/tests/sparse_param_test.py, examples/acados_python/tests/test_parametric_nonlinear_constraint_h.py, interfaces/CMakeLists.txt
- fix: `external_function_param_casadi` class for the case when the parameters are not a dense vector. This is still not recommended
- removed unused memory requirement of `np` in `external_function_param_casadi`.
- added static functions `d_cvt_ext_fun_arg_to_casadi`, `d_cvt_casadi_to_ext_fun_arg` to avoid code duplication
Tests:
- added `examples/acados_python/tests/sparse_param_test.py`
- improved test of parametric OCP formulation
=> Fix external casadi functions with sparse parameter definitions, remove unused memory, add tests

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/utils/external_function_generic.c, acados/utils/external_function_generic.h, interfaces/acados_c/external_function_interface.c, interfaces/acados_c/external_function_interface.h, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
Previously parameter values could be set function wise and stage wise.
- add external function classes: `external_function_external_param_casadi`, `external_function_external_param_generic`. These classes contain a pointer to the parameter values instead of a memory.
- Adjust OCP solver templates (single- and multi-phase) to use the new classes.
- Parameter vectors are now only stored once per stage in `ocp_nlp_in`
This allows to update parameters faster and lowers memory footprint. Moreover, it will be possible to get parameter values which allows to perform tests on parameters and more.
- Integrator not changes (yet). Benefit is that `external_function_param_casadi` is still tested.
=> Stagewise parameter values for OCP NLP solver

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, examples/acados_python/tests/test_nan_globalization.py, examples/acados_python/tests/test_osqp.py, interfaces/CMakeLists.txt
This PR adds Nan and Inf detection in merit function based line search. If Nan/inf is encountered during the evaluation of the merit function, the step size is decreased. If Nan/inf is encountered during the early termination check, no second-order corrections are performed.
Follow-up: backtrack if new linearization results in NaN or infeasible QP.
=> Detect Nan and Inf in merit function based line search

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, examples/acados_python/non_ocp_nlp/maratos_test_problem.py
- split into functions
- separate function for preliminary line search before SOC
- reset merit function weights when doing SOC. This is the only change affecting the behavior of the algorithm in this PR.
- adjusted test to account for point above.
=> Merit backtracking cleanup

examples/acados_matlab_octave/test/test_all_examples.m, examples/acados_matlab_octave/test/test_ocp_wtnx6.m, interfaces/acados_matlab_octave/acados_ocp.m, interfaces/acados_matlab_octave/acados_sim.m, interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/set_up_t_renderer.m, interfaces/acados_matlab_octave/check_dir_and_create.m, interfaces/acados_matlab_octave/create_consistent_empty_fields.m, interfaces/acados_matlab_octave/generate_c_code_disc_dyn.m, interfaces/acados_matlab_octave/generate_c_code_explicit_ode.m, interfaces/acados_matlab_octave/generate_c_code_ext_cost.m, interfaces/acados_matlab_octave/generate_c_code_gnsf.m, interfaces/acados_matlab_octave/generate_c_code_implicit_ode.m, interfaces/acados_matlab_octave/generate_c_code_nonlinear_constr.m, interfaces/acados_matlab_octave/generate_c_code_nonlinear_least_squares.m, interfaces/acados_matlab_octave/ocp_generate_c_code.m, interfaces/acados_matlab_octave/setup_ocp.m, interfaces/acados_matlab_octave/sim_generate_c_code.m, interfaces/acados_matlab_octave/sim_generate_casadi_ext_fun.m, interfaces/acados_template/acados_template/acados_ocp.py
This PR changes the code generation of CasADi functions in MATLAB such that it is solely based on the OCP description used of the template interface, i.e. `AcadosOcp`. Similar for integrators where only `AcadosSim` is used for code generation.
=> MATLAB: Code generation of CasADi functions based on `AcadosOcp`/`AcadosSim`

.github/workflows/full_build.yml, examples/acados_matlab_octave/test/create_ocp_qp_solver_formulation.m, examples/acados_matlab_octave/test/create_parametric_ocp_qp.m, examples/acados_matlab_octave/test/param_test.m, examples/acados_matlab_octave/test/run_matlab_tests.m, examples/acados_python/tests/test_parametric_nonlinear_constraint_h.py, interfaces/CMakeLists.txt, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_matlab_octave/acados_ocp.m, interfaces/acados_matlab_octave/ocp_get.c, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx, interfaces/acados_template/acados_template/acados_solver_common.pxd, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/mex_solver.in.m
- added functionality in Matlab interface: `ocp_solver.set_params_sparse(idx_values, new_p_values, stage);`. This updates the parameters with indices `idx_values` (0 based) at `stage` with the new values `new_p_values`.
- Added getters for parameter values `p` in Matlab and Python.
- Tests for parameter setters are added, both in Matlab and Python.
=> Sparse parameter update in Matlab and parameter getters

interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c
- empty array does not work with some compilers
- nothing has to be set if parameter vector is empty, thus added if in template
- reported in  https://discourse.acados.org/t/minimal-example-ocp-m-error/1702
- introduced in #1176
=> Hotfix sparse parameter setter Matlab for empty parameter and MSVC compiler

.gitmodules, docs/index.md
OSQP moved to a dedicated organization a while ago, so this updates all the docs references and the submodule to point to the new organization.
=> Fix links to OSQP to point to its new GitHub organization

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_constraints_bgh.c, acados/ocp_nlp/ocp_nlp_constraints_bgh.h, acados/ocp_nlp/ocp_nlp_constraints_bgp.c, acados/ocp_nlp/ocp_nlp_constraints_bgp.h, acados/ocp_nlp/ocp_nlp_constraints_common.h, acados/utils/types.h, examples/acados_python/tests/one_sided_constraints_test.py, examples/acados_python/tests/test_cython_ctypes.py, interfaces/CMakeLists.txt, interfaces/acados_matlab_octave/get_acados_infty.m, interfaces/acados_template/acados_template/__init__.py, interfaces/acados_template/acados_template/utils.py
- add `ACADOS_INFTY` in Python and C, `get_acados_infty` in Matlab.
- If any constraints have bounds `ACADOS_INFTY`, the constraint is marked as not relevant in the QP representation object `ocp_qp`, by setting the corresponding `d_mask` values to `0`.
- The underlying QP solver interface should make use of this mask.
- The HPIPM solvers do make use of this natively.
- For now the value is `ACADOS_INFTY=1e10` which might can be changed later after some more extensive testing.
- Support for that in QP solvers other than HPIPM is not included in this PR and tracked in https://github.com/acados/acados/issues/650
=> One sided constraint support for HPIPM solvers

acados/utils/external_function_generic.c
fixes call to `external_function_external_param_casadi_calculate_size`
- reported in https://github.com/acados/acados/issues/1186
- introduced in https://github.com/acados/acados/pull/1163
=> Fix `external_function_external_param_casadi`

.github/workflows/full_build.yml
- in order to check asserts on CI to avoid issues like https://github.com/acados/acados/issues/1186
=> Compile acados with `BUILD_TYPE = DEBUG` on Github actions

acados/dense_qp/dense_qp_daqp.c, examples/acados_python/tests/one_sided_constraints_test.py
See https://github.com/acados/acados/pull/1174 and https://github.com/acados/acados/issues/650
=> Use `d_mask` in DAQP interface to handle one-sided constraints

interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/compile_ocp_shared_lib.m
Since we only test Matlab/Octave on CI with Linux, we should use CMake to be closer to testing Windows workflow.
=> MEX: always use CMake for generated code

interfaces/acados_matlab_octave/AcadosOcp.m, interfaces/acados_matlab_octave/AcadosOcpCost.m, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_matlab_octave/detect_cost_type.m
- `AcadosOcpCost`: use "LINEAR_LS" as default cost_type as in Python for 0 cost as default
- `AcadosOcpOptions`:
- `qp_solver_ric_alg` = 1
- `qp_solver_cond_ric_alg` = 1
- `nlp_solver_max_iter` = 100
- dynamic defaults as in Python for: `alpha_min`, `alpha_reduction`, `eps_sufficient_descent`, `eval_residual_max_iter`, `full_step_dual`
=> New MATLAB frontend: change defaults to match Python

examples/acados_python/quadrotor_nav/common.py
Torsion should be a product of the normal and the derivative of the binormal with respect to arc-length.
Reference: [Minimum-time trajectory generation for quadrotors in constrained environments](https://arxiv.org/abs/1706.06478)
=> Correction: Torsion calculation in quadrotor_nav example

examples/acados_python/generic_dyn_disc/main.py, interfaces/acados_matlab_octave/AcadosOcp.m, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/c_templates_tera/CMakeLists.in.txt, interfaces/acados_template/acados_template/c_templates_tera/Makefile.in, interfaces/acados_template/acados_template/c_templates_tera/multi_Makefile.in
acados does not provide a standalone integrator if discrete dynamics are used. This PR adapts the python and MATLAB interface to not code generate any files related to the integrator if discrete dynamics are used.
- closes https://github.com/acados/acados/issues/1224
=> No code generation for integrator and related files if dynamics are DISCRETE

interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
and rename ERK related functions for consistency.
=> Include external function needed for ERK adjoints properly in solver templates

interfaces/acados_matlab_octave/GenerateContext.m, interfaces/acados_template/acados_template/casadi_function_generation.py
If the CasADi version supports common subexpression elimination, the corresponding option is set when creating CasADi functions.
Closes https://github.com/acados/acados/issues/1207
=> Add common subexpression elimination to CasADi function creation

acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_ddp.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp.h, examples/c_ext_dep_off/pendulum/main_pendulum_ode.c, interfaces/acados_matlab_octave/AcadosOcp.m, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx, interfaces/acados_template/acados_template/c_templates_tera/main_multi.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c
closes #1255 
BREAKING: setting option `rti_phase` for NLP solvers other than `SQP_RTI` is not supported anymore.
=> Remove `rti_phase` from DDP and SQP

examples/acados_matlab_octave/p_global_example/create_ocp_formulation_without_opts.m, examples/acados_matlab_octave/p_global_example/main.m
- fix options, have to be provided in `mocp.solver_options`
- test with custom block sizes in partial condensing
=> MATLAB: Blazing MOCP example

interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/compile_ocp_shared_lib.m
relevant only for MATLAB on linux
=> MATLAB: compile only OCP solver lib in `compile_ocp_shared_lib`

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_sqp.c, examples/acados_matlab_octave/getting_started/extensive_example_ocp.m, examples/acados_matlab_octave/mocp_transition_example/main_multiphase_ocp.m, examples/acados_python/mocp_transition_example/main.py, examples/acados_python/pendulum_on_cart/ocp/example_custom_hessian.py, examples/acados_python/tests/armijo_test.py, examples/acados_python/unconstrained_ocps/hour_glass_p2p_motion/hour_glass_time_optimal_p2p_motion.py, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_matlab_octave/AcadosOcpIterate.m, interfaces/acados_matlab_octave/AcadosOcpIterates.m, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_matlab_octave/AcadosOcpSolver.m, interfaces/acados_matlab_octave/acados_ocp_opts.m, interfaces/acados_matlab_octave/ocp_get.c, interfaces/acados_matlab_octave/setup_AcadosOcp_from_legacy_ocp_description.m, interfaces/acados_template/acados_template/acados_ocp_iterate.py, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/mex_solver.in.m
* move `max_iter` to `ocp_nlp_common`
* add solver option `store_iterates`
* if `store_iterates` is true, the iterates are stored during the SQP/DDP loop and can be accessed after the solve from MATLAB/python
* not available for real-time solvers
In addition:
* add getter for `'nlp_iter'` in MATLAB
=> Store intermediate iterates

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_qp/ocp_qp_xcond_solver.c, acados/utils/strsep.h
`ptr_module` was used uninitialized if no `_` was given
=> Fix for `extract_module_name`

interfaces/acados_template/acados_template/c_templates_tera/cost.in.h
`ost_ext_cost_fun_jac_get_pool_double` -> `cost_ext_cost_fun_jac_get_pool_double`
=> `p_global`: fix typo in generated cost header

acados/ocp_nlp/ocp_nlp_ddp.h, acados/ocp_nlp/ocp_nlp_sqp.h
Since option was moved to common in #1262
=> Remove unused internal variable `max_iter` in DDP and SQP

interfaces/acados_matlab_octave/acados_ocp_opts.m, interfaces/acados_matlab_octave/setup_AcadosOcp_from_legacy_ocp_description.m, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
This PR
* adds `sim_method_newton_tol` to the old MATLAB interface
* sets the option in the (M)OCP solver templates
=> Set `sim_method_newton_tol` in solver templates 

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c
This allows one to solve QPs with data other than the default `qp_in` and `qp_out`.
=> C: generalize `ocp_nlp_solve_qp_and_correct_dual` with optional arguments

interfaces/acados_matlab_octave/AcadosOcpSolver.m, interfaces/acados_template/acados_template/acados_ocp_solver.py
Before, MATLAB crashes without error when switching to `SQP_RTI` in `examples/acados_matlab_octave/getting_started/extensive_example_ocp.m`.
=> get_iterate: check if `nlp_solver_type` is supported in interfaces

.github/workflows/full_build.yml, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_nlp/ocp_nlp_sqp_rti.h, examples/acados_python/tests/test_rti_sqp_residuals.py, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
- add option `rti_log_only_available_residuals`: 
"""Relevant if rti_log_residuals is set to 1.
If `rti_log_only_available_residuals` is set to 1, only residuals that do not require additional function evaluations are logged."""
- Python: add fields res_ineq_all, res_comp_all to get_stats
- add test_rti_sqp_residuals and run on CI: test consistency between RTI and SQP residuals
=> Fix RTI residuals

interfaces/acados_matlab_octave/setup_AcadosOcp_from_legacy_ocp_description.m
This PR fixes the transcription of the field `shooting_nodes` from the old to the new solver interface.
=> MATLAB: add shooting nodes to solver transcription

examples/acados_python/chain_mass/solution_sensitivity_example.py, interfaces/acados_template/acados_template/acados_ocp_solver.py
This PR adds the functions `store_to_obj` and `load_from_obj` to the python interface. These functions allow to store/load the current iterate to/from an AcadosOcpIterate object.
In addtion, `get_iterate` now allows to get the last iterate by setting `iteration=-1`
Closes https://github.com/acados/acados/issues/1219
=> Python: Store/Load iterate to/from AcadosOcpIterate

interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_matlab_octave/AcadosSimOptions.m, interfaces/acados_matlab_octave/acados_ocp_opts.m, interfaces/acados_matlab_octave/acados_sim_opts.m, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_sim.py
This PR changes the default value for  `ext_fun_compile_flag`:
-  If the environment variable `ACADOS_EXT_FUN_COMPILE_FLAG` is set, it is used as default.
- Otherwise, the old default `-O2` is used.
=> MATLAB/python: Default value for `ext_fun_compile_flag` from environment variable

.github/workflows/ext_dep_off.yml, .github/workflows/full_build.yml
In this way the artifacts uploaded are compiled with Release which is nice when using them in other projects.
=> Github Actions: use Release in full_build, and Debug in ext_dep_off

.github/workflows/full_build.yml, acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_cost_conl.c, acados/ocp_nlp/ocp_nlp_cost_external.c, acados/ocp_nlp/ocp_nlp_cost_external.h, acados/ocp_nlp/ocp_nlp_cost_ls.c, acados/ocp_nlp/ocp_nlp_cost_nls.c, acados/ocp_nlp/ocp_nlp_dynamics_disc.c, acados/ocp_nlp/ocp_nlp_dynamics_disc.h, acados/sim/sim_erk_integrator.c, acados/sim/sim_gnsf.c, acados/sim/sim_irk_integrator.c, acados/sim/sim_lifted_irk_integrator.c, examples/acados_python/chain_mass/solution_sensitivity_example.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/policy_gradient_example.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/sensitivity_utils.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/value_gradient_example.py, interfaces/CMakeLists.txt, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.pxd, interfaces/acados_template/acados_template/casadi_function_generation.py, interfaces/acados_template/acados_template/utils.py
Solution sensitivities with respect to parameters and derivatives of the value function with respect to parameters are now computed with respect to `p_global` instead of `p`. This is anyway what was implemented conceptually. However, if different parameter values for stages were used, these sensitivities were not clearly defined.
The precomputations and the fact that the parameter vector is only defined once makes this implementation more efficient.
- added support for `p_global` in Cython
Breaking:
- concerns options `with_solution_sens_wrt_params`, `with_solution_sens_wrt_params`
- `eval_solution_sensitivity` with argument `with_respect_to = "params_global"`
- `eval_and_get_optimal_value_gradient` with argument `with_respect_to = "params_global"`
- rename option …
=> Migrate sensitivities of solution and value function of parameters to `p_global`

acados/ocp_nlp/ocp_nlp_cost_external.c
=> Fix memory corresponding to `p_global` in EXTERNAL cost module

examples/acados_python/pendulum_on_cart/ocp/ocp_example_cost_formulations.py, interfaces/acados_template/acados_template/acados_ocp.py
This PR add the function `translate_cost_to_external_cost` to the class `AcadosOcp`. It allows to reformulate costs of type `LINEAR_LS`, `NONLINEAR_LS` and `CONVEX_OVER_NONLINEAR` as costs of type `EXTERNAL`.
=> Python: Add translate functionality from LS/NLS/CONL cost to external cost

.github/workflows/full_build.yml, acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp.h, examples/acados_python/chain_mass/solution_sensitivity_example.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/forw_vs_adj_param_sens.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/sensitivity_utils.py, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/casadi_function_generation.py, interfaces/acados_template/acados_template/utils.py
- can be used from Python via `AcadosOcpSolver.eval_adjoint_solution_sensitivity()`
```
Evaluate the adjoint sensitivity of the solution with respect to the parameters.
:param seed_x : np.ndarray or list of np.ndarrays - seed for the states at stage `stages`
:param seed_u : np.ndarray or list of np.ndarrays - seed for the controls at stage `stages`
:param stages_seed_x : int or list of int - stages corresponding to the seeds_x
:param stages_seed_u : int or list of int - stages corresponding to the seeds_u
:param with_respect_to : string in ["p_global"]
:param sanity_checks : bool - whether to perform sanity checks, turn off for minimal overhead, default: True
```
- chain-mass example `solution_sensitivity_example.py`: fix wrt global parameters, extend to also evaluate an adjoint …
=> Adjoint solution sensitivities with respect to global parameters

examples/acados_python/chain_mass/plot_utils.py, examples/acados_python/chain_mass/solution_sensitivity_example.py, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_template/acados_template/acados_ocp_iterate.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c
- C: implement new functions `ocp_nlp_dims_get_total_from_attr`,  `ocp_nlp_get_all`, `ocp_nlp_set_all`
- Python: implement `AcadosOcpFlattenedIterate`, `AcadosOcpSolver.store_iterate_to_flat_obj`, `AcadosOcpSolver.load_iterate_from_flat_obj`
- Simulink: simplify logic using the new functions in the C interface.
The flat iterates are now used in the chain sensitivity example and show significant speedup.
Timings before with `AcadosOcpIterate` object:
Timings now with `AcadosOcpFlattenedIterate` object:
=> Implement getter and setter for values of the whole horizon

.github/workflows/codeql.yml
v3 will be deprecated soon, see
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> CI: codeql use upload-artifact@v4

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_constraints_bgh.c, acados/ocp_nlp/ocp_nlp_constraints_bgh.h, acados/ocp_nlp/ocp_nlp_constraints_bgp.c
- set `np_global` in constraints
- simplify dimension getters and setters
- add dimensions nb, ng, ni_nl to `ocp_nlp_dims`
=> C: work on constraint dimensions

acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_rti.c, examples/acados_python/tests/test_rti_sqp_residuals.py, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_matlab_octave/AcadosOcp.m, interfaces/acados_template/acados_template/acados_ocp_solver.py
- Python: implement convenience function `get_initial_residuals ` which are the residuals that always come for free in RTI, in the sense that they don't require additional external function evaluations
- C: call `eval_kkt_residual` in `eval_residuals`
- Python: when solver is RTI or `recompute` is True, `get_residuals` computes the correct residuals when updating parameters or other problem data.
- implement `eval_kkt_residual` for all NLP solvers.
- test correct behavior
- Simulink output port `KKT_residuals` now also computes the residuals correctly in case of RTI. This can significantly increase the turnaround time of the Simulink block when the output port is activated!
=> Fix `get_residuals`

.github/workflows/full_build.yml, acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_constraints_bgh.c, acados/utils/external_function_generic.c, examples/acados_python/pendulum_on_cart/solution_sensitivities/sensitivity_utils.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/value_gradient_example_linear.py, interfaces/acados_template/acados_template/casadi_function_generation.py
- fixed external function generation: output should be column vector
- external functions: use `exit` instead of assert to also check when compiling with Release
- `ocp_nlp_common_eval_lagr_grad_p`: pass correct option pointers to submodules
- fix adj_p in constraint module with nh==0
- add new example and improved plot
=> Fix value function sensitivities, add example varying parameters in certain direction on linear OCP

examples/acados_matlab_octave/mocp_transition_example/main_multiphase_ocp.m, examples/acados_python/mocp_transition_example/minimal_transition_example.py, interfaces/acados_matlab_octave/AcadosOcp.m, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
This allows to have `AcadosOcp.shooting_nodes` be "correct" when incorporating transition stages with costs.
Simplified transition examples accordingly.
```
cost_scaling: 
Vector with cost scaling factors of length N_horizon + 1.
If None set automatically to [`time_steps`, 1.0].
Default: None
```
Improved docstrings for `time_steps` and `shooting_nodes`
=> Add option `cost_scaling` in template based interfaces

examples/acados_python/pendulum_on_cart/ocp/minimal_example_batch_ocp_solver.py, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_template/acados_template/acados_ocp_batch_solver.py, interfaces/acados_template/acados_template/acados_ocp_iterate.py, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
This PR extends the solver `AcadosOcpBatchSolver` with 
- `get_flat` to get the flattened iterate from all solvers in the batch
- `store_iterate_to_flat_obj` and `load_iterate_from_flat_obj` which allow to load/store a batch iterate
=> C templates/python: Extend batch solver with load/store from/to flattenedd batch iterate

acados/ocp_nlp/ocp_nlp_common.c, examples/acados_python/pendulum_on_cart/solution_sensitivities/forw_vs_adj_param_sens.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/policy_gradient_example.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/sensitivity_utils.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/state_augementation_policy_gradient.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/value_gradient_example.py, interfaces/acados_template/acados_template/acados_ocp.py
- allow constraints that are nonlinear in `p_global`
- improved examples and tests
- difference in forward vs. adjoint on the problem when using longer horizon might be due to numerical errors. For smaller problem the sensitivities match, although constraint is active. But one might check more closely.
=> Sensitivities with parametric constraints: follow-up to #1345

examples/acados_matlab_octave/getting_started/extensive_example_ocp.m, examples/acados_matlab_octave/legacy_interface/getting_started/extensive_example_ocp.m, examples/acados_matlab_octave/pendulum_on_cart_model/example_ocp.m, examples/acados_python/pendulum_on_cart/solution_sensitivities/policy_gradient_example.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/state_augementation_policy_gradient.py, interfaces/acados_matlab_octave/AcadosOcpSolver.m, interfaces/acados_template/acados_template/acados_ocp_solver.py
The QP diagnostic function now returns a dict/struct with consistent names
- `min_eigv_stage`
- `max_eigv_stage`
- `condition_number_stage`
- `condition_number_global`
- `min_eigv_global`
- `min_abs_eigv_global`
- `max_eigv_global`
- `min_eigv_P_global` for projected Hessian only
- `min_abs_eigv_P_global` for projected Hessian only
In addition:
- improve docstring
- python: return list instead of dict for stagewise values, reduce redundancy
=> MATLAB/python: QP diagnostic with consistent names

interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_template/acados_template/acados_ocp_options.py
BREAKING: changed default value for `nlp_solver_type` from "SQP_RTI" to "SQP".
This makes it more robust and is more expected behavior for people that start using acados, e.g. https://github.com/acados/acados/issues/1365
=> Python & Matlab: use SQP by default

examples/acados_python/solution_sensitivities_convex_example/batch_adjoint_solution_sensitivity_example.py
* Minor cleanup
* In addition to the initial state, we now also vary the values of `p_global`
=> Python: Cleanup of batch sensitivity example, vary `p_global`

examples/acados_python/chain_mass/solution_sensitivity_example.py, examples/acados_python/pendulum_on_cart/example_solution_sens_closed_loop.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/forw_vs_adj_param_sens.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/policy_gradient_example.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/state_augementation_policy_gradient.py, examples/acados_python/pendulum_on_cart/solution_sensitivities/test_solution_sens_and_exact_hess.py, interfaces/acados_template/acados_template/acados_ocp_batch_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver.py
The additional, optional fields `return_sens_x`, `return_sens_u`, `return_sens_pi`, `return_sens_lam`, `return_sens_su`, `return_sens_sl` allow to specify which sensitivities should be returned.
Breaking: The return type of  `eval_solution_sensitivity` changes: We now return a dict with fields `sens_x`, `sens_u`, `sens_pi`, `sens_lam`, `sens_su`, `sens_sl` if the corresponding flag has been set.
=> Python: allow getting sensitivities wrt. `pi`, `lam`, `sl`, `su`

examples/acados_python/p_global_example/example_p_global.py, interfaces/acados_template/acados_template/acados_model.py, interfaces/acados_template/acados_template/acados_multiphase_ocp.py, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/casadi_function_generation.py, interfaces/acados_template/acados_template/mpc_utils.py, interfaces/acados_template/acados_template/utils.py
Before, we inconsistently used `None` and `[]`.
For CasADi expressions `[]` is more suitable, since it is compatible with `casadi.vertcat`.
Breaking: default types of fields in `AcadosModel` that might be symbolic have changed to `[]`.
=> Python: use [] as default for CasADi expressions consistently

interfaces/acados_matlab_octave/AcadosMultiphaseOcp.m, interfaces/acados_matlab_octave/AcadosOcp.m, interfaces/acados_template/acados_template/acados_multiphase_ocp.py, interfaces/acados_template/acados_template/acados_ocp.py
This PR ignores non-required stages in code generation for multi-phase OCPs. This way the code generation overhead is reduced. If global parameters are used, this might also avoid the computation of parametric expressions which are not needed.
=> Python/Matlab: More efficient code generation for MOCP models

examples/acados_matlab_octave/getting_started/extensive_example_ocp.m, examples/acados_matlab_octave/legacy_interface/getting_started/extensive_example_ocp.m, interfaces/acados_matlab_octave/AcadosOcpSolver.m, interfaces/acados_matlab_octave/ocp_get.c
- Fix getter for QP matrices and vectors at the terminal stage.
- Fix `dump_last_qp_to_json` to include constraint-related terms at terminal stage.
=> MATLAB: fix getter for QP values at terminal stage

interfaces/acados_matlab_octave/GenerateContext.m, interfaces/acados_template/acados_template/casadi_function_generation.py
We do not support the case where the model contains global parameters, but no CasADi function depends on them. This PR adds a corresponding check and raises a corresponding exception during code generation.
=> MATLAB/Python: Add check whether `p_global` is defined, but `global_data` is empty

interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_sim.py, interfaces/acados_template/acados_template/acados_sim_solver.py, interfaces/acados_template/acados_template/casadi_function_generation.py
- use `get_casadi_symbol()` from `AcadosModel` in code generation
- move `generate`, `dump_to_json`, `render_templates` to `AcadosSim` (which is consistent with `AcadosOcpSolver`)
- improve docstring in `AcadosOcpSolver.options_set()`, allow `nlp_solver_max_iter`
=> Python: Cleanup code generation, sim solver

examples/acados_matlab_octave/mocp_transition_example/main_mocp_simulink.m, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/make_sfun.in.m
This PR
* fixes the dimension `nh_total` in sfunction creation
* improves the MOCP simulink test by testing with `nbx != nh`
=> Simulink: Fix `nh_total` dimension in sfunction

interfaces/acados_template/acados_template/acados_ocp_batch_solver.py, interfaces/acados_template/acados_template/acados_sim_batch_solver.py
This PR adds the  `build` and `generate` flags to the batch OCP solver and batch sim solver indicating whether the solver should be (re)compiled and the problem functions should be (re)generated, respectively.
=> Python: `build` and `generate` flags for batch solvers

interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_template/acados_template/acados_ocp_batch_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
This PR fixes the solver status in batch solves. 
BREAKING: the templated function `{{ model.name }}_acados_batch_solve` now requires an additional input  `int * status_out`  for storing the solver status for each solve in the batch.
=> C/Python: Fix solver status in batch solve

examples/acados_matlab_octave/test/param_test.m, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_matlab_octave/ocp_get.c, interfaces/acados_template/acados_template/c_templates_tera/main.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c
This PR uses flat getters and setters in the MATLAB interface. This makes existing full trajectory getters/setters more efficient and adds support for full trajectory setters for `lam`, `sl`, `su`, `z`.
NOTE: setting `solver.set('p', vals) ` allows to
* set the same `p` vector for every stage, i.e. `size(vals) = [np, 1]`,
* set the full `p` trajectory.
The first option is *only* available for `p` (and not for any of the other setters).
In addition:
* fix missing `;` in generated main
=> MATLAB: Use flat getters and setters

examples/acados_matlab_octave/mocp_transition_example/main_multiphase_ocp.m, examples/acados_python/pendulum_on_cart/mhe/closed_loop_mhe_ocp.py, examples/acados_python/pendulum_on_cart/mhe/export_mhe_solver.py, examples/acados_python/pendulum_on_cart/mhe/export_mhe_solver_with_param.py, examples/acados_python/pendulum_on_cart/mhe/minimal_example_mhe.py, examples/acados_python/pendulum_on_cart/mhe/minimal_example_mhe_with_noisy_param.py, examples/acados_python/pendulum_on_cart/mhe/minimal_example_mhe_with_param.py
Minor changes to examples:
MATLAB: showcase initialization of MOCP solvers using flat format.
Python: Cleanup MHE examples.
=> MATLAB/Python: Cleanup examples

examples/acados_matlab_octave/mocp_transition_example/main_mocp_simulink.m, examples/acados_matlab_octave/p_global_example/simulink_test_p_global.m, examples/acados_matlab_octave/test/exit_with_error.m, examples/acados_matlab_octave/test/simulink_init_test.m, examples/acados_matlab_octave/test/simulink_param_test.m, examples/acados_matlab_octave/test/simulink_qp_test.m, examples/acados_matlab_octave/test/simulink_slack_test.m, examples/acados_matlab_octave/test/simulink_sparse_param_test.m, examples/acados_matlab_octave/test/simulink_test.m, examples/acados_matlab_octave/test/test_ocp_OSQP.m, examples/acados_matlab_octave/test/test_ocp_qpdunes.m
This PR replaces all calls to `quit()` in the examples and tests with `error()` as `quit()` closes MATLAB.
=> MATLAB: no `quit()`

interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c
The function `ocp_nlp_dims_get_total_from_attr` now additionally supports the fields:
- `zl`, `zu`, `Zl`, `Zu`
- `cost_z`, `cost_Z`
- `lbx`, `ubx`, `nbx`
- `lbu`, `ubu`, `nbu`
- `lg`, `ug`, `ng`
- `lh`, `uh`, `nh`
In addition, this fixes a bug in `ocp_nlp_dims_get_from_attr` which now correctly returns `2*ns` for `s`, `cost_z`, `cost_Z`.
BREAKING: The function `ocp_nlp_dims_get_total_from_attr` now requires the additional argument `ocp_nlp_out *out,`
=> C: More  total dimension getters

acados/utils/strsep.h, examples/acados_matlab_octave/mocp_transition_example/main_parametric_mocp.m, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c
This PR adds the option to use the flat format for setting the values of
- `cost_zl`, `cost_zu`, `cost_Zl`, `cost_Zu`
- `constr_lbx`, `constr_ubx`, `constr_lbu`, `constr_ubu`, `constr_lbg`, `constr_ubg`, `constr_lbh`, `constr_ubh`
over the whole horizon.
In addition, fixes bug in dimension getter for `cost_Z`, `cost_z` introduces in https://github.com/acados/acados/pull/1416.
=> MATLAB/C: more flat setters in interface

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_ddp.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp.h, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_nlp/ocp_nlp_sqp_rti.h, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
Implement option `nlp_solver_warm_start_first_qp_from_nlp`, if True first QP will be initialized using values from NLP iterate, otherwise from previous QP solution, only relevant if `nlp_solver_warm_start_first_qp` is True. Default: False.
The new initialization (with `nlp_solver_warm_start_first_qp = True`) is likely beneficial.
We might change the default behavior after more testing.
Fixed option `warm_start_first_qp` for SQP-RTI.
=> QP warm-start in first NLP solver iteration

.github/workflows/c_test_blasfeo_reference.yml, .github/workflows/codeql.yml, .github/workflows/ext_dep_off.yml
Mail from Github:
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025.
=> Github Actions: switch to ubuntu-22.04

interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
Remove warning in `set_p_global_and_precompute_dependencies` if global data is empty as it can be distracting, especially when using a `AcadosOcpBatchSolver`.
=> Remove: no global data warnings

acados/ocp_qp/ocp_qp_full_condensing.c, acados/ocp_qp/ocp_qp_full_condensing.h, examples/c/no_interface_examples/mass_spring_offline_fcond_qpoases_split.c
- Plus update HPIPM
- See https://github.com/giaf/hpipm/commit/f49620429d79146a3a891f618ff4816f04a9481b
=> Condensing: call `d_cond_qp_expand_sol` with options as `d_cond_qp_expand_primal_sol` was removed in HPIPM

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_cost_external.c, acados/ocp_nlp/ocp_nlp_reg_common.c, acados/ocp_nlp/ocp_nlp_reg_common.h, acados/ocp_nlp/ocp_nlp_reg_mirror.c, acados/ocp_nlp/ocp_nlp_reg_mirror.h, acados/ocp_nlp/ocp_nlp_reg_project.c, acados/ocp_nlp/ocp_nlp_reg_project.h, examples/acados_python/non_ocp_nlp/adaptive_eps_reg_test.py, examples/acados_python/non_ocp_nlp/regularization_test.py, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
New options:
- `reg_max_cond_block`: Maximum condition number per block when using regularize_method in ['PROJECT', 'MIRROR'] with `reg_adaptive_eps` = True, Default: 1e-7
- `reg_adaptive_eps`: Determines if epsilon is chosen adaptively in regularization used if regularize_method in ['PROJECT', 'MIRROR']
If true, epsilon is chosen block-wise based on `reg_max_cond_block`.
Otherwise, epsilon is chosen globally based on `reg_epsilon`.
Default: False
Inspired by "A nonmonotone filter SQP method: local convergence and numerical results" by NICHOLAS I. M. GOULD, YUELING LOH,  DANIEL P. ROBINSON, Sec. 5.1
=> Implement adaptive epsilon for regularizations: `MIRROR` and `PROJECT`

acados/ocp_nlp/ocp_nlp_reg_common.c, acados/ocp_nlp/ocp_nlp_reg_common.h, acados/ocp_nlp/ocp_nlp_reg_mirror.c, acados/ocp_nlp/ocp_nlp_reg_mirror.h, acados/ocp_nlp/ocp_nlp_reg_project.c, acados/ocp_nlp/ocp_nlp_reg_project.h, examples/acados_python/non_ocp_nlp/adaptive_eps_reg_test.py, interfaces/CMakeLists.txt, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
- fix test, run test on CI
- add option: `reg_min_epsilon`: Minimum value for epsilon if regularize_method in ['PROJECT', 'MIRROR'] is used with reg_adaptive_eps. Default: 1e-8.
- fix `reg_max_cond_block` default: 1e7 instead of 1e-7. Add check that it must be >= 1.0.
=> Follow up to #1462

acados/ocp_nlp/ocp_nlp_reg_glm.c, acados/ocp_nlp/ocp_nlp_reg_glm.h, acados/utils/math.c, acados/utils/math.h, examples/acados_python/non_ocp_nlp/adaptive_eps_reg_test.py, interfaces/acados_c/ocp_nlp_interface.c, interfaces/acados_c/ocp_nlp_interface.h, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
Implement new regularization module: `GERSHGORIN_LEVENBERG_MARQUARDT`.
Estimates the smallest eigenvalue of each Hessian block using Gershgorin circles and adds multiple of identity to each block, such that smallest eigenvalue after regularization is at least `reg_epsilon`.
=> Gershgorin Levenberg Marquardt regularization

examples/acados_python/tests/armijo_test.py, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/utils.py
Breaking: `cost_expr_ext_cost_custom_hess*` can not be float or int anymore in Python, but should be a CasADi MX/SX/DM
=> Python: checks on external checks

.github/workflows/full_build.yml, examples/acados_python/pendulum_on_cart/ocp/ocp_example_cost_formulations.py, interfaces/CMakeLists.txt, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_cost.py, interfaces/acados_template/acados_template/utils.py
This PR extends the Python interface to acados by enabling symbolic expressions for the following cost matrices and reference vectors:
- `W_0` (initial stage cost weight matrix)
- `W` (stage cost weight matrix)
- `W_e` (terminal cost weight matrix) 
- `yref_0` (initial stage reference vector)
- `yref` (stage reference vector)
- `yref_e` (terminal reference vector)
This enhancement allows for parameterized least-squares cost functions. The least-squares cost is translated to an external cost, and parameters can be dynamically modified at runtime.
This is particularly valuable for advanced two-solver implementations where:
1. A forward solver leverages a Gauss-Newton Hessian approximation
2. A backward solver employs an exact Hessian for exact sensitivity computation
=> Symbolic cost parameters

interfaces/acados_template/acados_template/acados_ocp.py
Refactor the external cost translation into three specialized methods:
- `translate_cost_0_term_to_external` (initial)
- `translate_cost_term_to_external` (intermediate)
- `translate_cost_e_term_to_external` (terminal)
This modular approach simplifies translation based on `yref_0`, `yref`, `yref_e` and `W_0`, `W`, `W_e` definitions without requiring direct handling of parameters (`p`, `p_values`, `p_global`, `p_global_values`).
=> Stagewise translate

examples/acados_python/pendulum_on_cart/ocp/minimal_example_batch_ocp_solver.py, examples/acados_python/pendulum_on_cart/sim/minimal_example_batch_sim_solver.py, examples/acados_python/solution_sensitivities_convex_example/batch_adjoint_solution_sensitivity_example.py, examples/acados_python/solution_sensitivities_convex_example/setup_parametric_ocp.py, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_matlab_octave/AcadosSimOptions.m, interfaces/acados_template/acados_template/acados_ocp_batch_solver.py, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_sim.py, interfaces/acados_template/acados_template/acados_sim_batch_solver.py, interfaces/acados_template/acados_template/c_templates_tera/CMakeLists.in.txt, interfaces/acados_template/acados_template/c_templates_tera/Makefile.in, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h, interfaces/acados_template/acados_template/c_templates_tera/multi_Makefile.in
Previously, the number of threads to be used in the `AcadosOcpBatchSolver` or `AcadosSimBatchSolver` batched methods had to be set in the respective `AcadosOcpOptions` or `AcadosSimOptions` and could not be changed without rebuilding the solver.
Now, it is a property that can be set dynamically, even after building the solver.
The property `num_threads_in_batch_solve` in both `AcadosOcpOptions` and `AcadosSimOptions` is now deprecated,
and warnings will be printed if it is used.
Instead, the `AcadosOcpBatchSolver` and `AcadosSimBatchSolver` have a new (settable) property `num_threads_in_batch_solve` and take the initial value in their constructor via a new `num_threads_in_batch_solve` argument. 
The value of the new attribute is now used to determine how many threads the batched methods …
=> Dynamic num threads in batch solvers

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp.h, acados/ocp_nlp/ocp_nlp_sqp_with_feasible_qp.c, acados/ocp_nlp/ocp_nlp_sqp_with_feasible_qp.h, examples/acados_matlab_octave/getting_started/extensive_example_ocp.m, examples/acados_python/pendulum_on_cart/ocp/example_ocp_dynamics_formulations.py, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_matlab_octave/ocp_get.c, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c, interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
-  move primal_step_norm to common memory, as option is also there
-  Interfaces: fix log_primal_step_norm for SQP_WFQP and multi-phase 
- add option ` log_dual_step_norm`
- test getting step norms in MATLAB and Python
Bit unrelated:
-  SQP_WFQP: remove max_iter duplicated from common
=> Step norm logging

acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp_with_feasible_qp.c, acados/ocp_nlp/ocp_nlp_sqp_with_feasible_qp.h, examples/acados_python/non_ocp_nlp/maratos_test_problem.py
Follow-up of https://github.com/acados/acados/pull/1492.
The changed tests in https://github.com/acados/acados/pull/1492 have been reverted as the iteration reference was still wrong there. Now I verified by printing.
=> C: avoid using local variable `sqp_iter`

examples/acados_matlab_octave/race_cars/main.m, examples/acados_matlab_octave/test/create_ocp_qp_solver_formulation.m, examples/acados_matlab_octave/test/create_parametric_ocp_qp.m, examples/acados_python/race_cars/acados_settings.py, examples/acados_python/race_cars/acados_settings_dev.py, interfaces/acados_template/acados_template/acados_ocp.py
- NOTE: function `AcadosOcp.translate_initial_cost_term_to_external` recently introduced has now a new name.
=> Fix typo: intial -> initial

interfaces/acados_template/acados_template/acados_multiphase_ocp.py, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_batch_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_sim_batch_solver.py
- add verbose to `make_consistent()` for `AcadosOcp` and `AcadosMultiphaseOcp`
- for batch solvers: only use verbose when creating the first solver
=> Python verbosity

interfaces/acados_template/acados_template/acados_model.py
When not set, `u_labels` were wrongly initialized with the dimension of `x`.
=> Python: fix `u_labels` init

acados/utils/external_function_generic.c, interfaces/acados_matlab_octave/GenerateContext.m, interfaces/acados_template/acados_template/casadi_function_generation.py
By making it dense in the MATLAB & Python interfaces.
=> Fix `p_global` precomputation in case sparse data is detected

interfaces/acados_template/acados_template/acados_casadi_ocp_solver.py
- organized the variables along time nodes as $x_0, x_1,....,x_{N+1}$ and $u_0, u_1...., u_N$ and then vectorized them in the interleaved order as $x_0, u_0, x_1, u_1...., x_N, u_N,x_{N+1}$.
- I also adjust the `get()` function to get solution values in an interleaved manner.
=> Reorder variables in `AcadosCasadiOcpSolver`

interfaces/acados_template/acados_template/c_templates_tera/CMakeLists.in.txt, interfaces/acados_template/acados_template/c_templates_tera/Makefile.in, interfaces/acados_template/acados_template/c_templates_tera/main.in.c
`N_horizon` should get the default value 1 in templates only if we render them to get a sim solver. Previously 0 was overwritten by 1 there.
=> fix `N_horizon` check in templates

interfaces/acados_template/acados_template/acados_sim.py
The number of stages is per default 4 and not 1 as stated in the doc string.
Please look at the screenshot ([or code](https://github.com/acados/acados/blob/main/interfaces/acados_template/acados_template/acados_sim.py#L82)) to confirm.
To me this was a bit surprising since I tried to play around with this property.
=> [docs] Fix mistake in doc string of acados sim object for num of stages

interfaces/acados_template/acados_template/acados_ocp.py
The function didn't consider dual variables corresponding to the bounds of slack variables.
=> Python: fix `create_default_initial_iterate` wrt slack variables

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_ddp.h, acados/ocp_nlp/ocp_nlp_sqp.c, acados/ocp_nlp/ocp_nlp_sqp.h, acados/ocp_nlp/ocp_nlp_sqp_rti.c, acados/ocp_nlp/ocp_nlp_sqp_rti.h, acados/ocp_nlp/ocp_nlp_sqp_with_feasible_qp.c, acados/ocp_nlp/ocp_nlp_sqp_with_feasible_qp.h
We moved the solution tolerances, `warm_start_qp`-opts, and `eval_residual_at_max_iter` to `ocp_nlp_common`.
This removes redundancy in the code and makes tolerances available in cases where only `ocp_nlp_opts` is available.
=> Move options from solvers to `ocp_nlp_common`

acados/ocp_nlp/ocp_nlp_common.c
Bug fix in calculation of inf norm of lam. The for loop should go until N, i.e., `<=N`.
=> Bug fix in `ocp_nlp_compute_dual_lam_norm_inf`

examples/acados_python/solution_sensitivities_convex_example/non_ocp_example.py, interfaces/acados_matlab_octave/AcadosOcp.m, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_options.py, interfaces/acados_template/acados_template/acados_ocp_solver.py
-  deprecate string "params_global"
-  example: call `setup_qp_matrices_and_factorize`, add variant without squared parameter
- Interface: `setup_qp_matrices_and_factorize` also works with `FULL_CONDENSING_HPIPM`
- set `dims.nbxe_0 = 0` for `N_horizon = 0` for consistency
=> Python: solution sensitivity update

interfaces/acados_template/acados_template/acados_ocp_batch_solver.py
When `Verbose` is set to `False`, to reduce the amount of printing in projects such as `leap-c`
=> Python: allow suppressing the note about `OpenMP` in `AcadosOcpBatchSolver`

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_globalization_merit_backtracking.c
The Second-Order Correction functionality was moved from `ocp_nlp_globalization_merit_backtracking` to `ocp_nlp_common` such that it can be used for other globalized algorithms as well.
=> Moved Second-Order Correction to function in `ocp_nlp_common`

acados/ocp_nlp/ocp_nlp_globalization_funnel.c
The predicted reduction in the merit function in the penalty phase was not calculated correctly. 
For the `NOMINAL`-step mode, the previous version was correct, but for `BYRD_OMOJOKUN`, it was wrong.
=> Bug fix in FUNNEL globalization

acados/ocp_nlp/ocp_nlp_globalization_funnel.c, acados/ocp_nlp/ocp_nlp_globalization_funnel.h
The Armijo condition was wrong for the `f`-type steps and also for the `p`-type steps. This was corrected by introducing a funtion that checks the Armijo condition and which can be used either for `f`- or `p`-type steps.
=> Major bug fix in `FUNNEL_L1PEN_LINESEARCH`

examples/acados_matlab_octave/getting_started/extensive_example_ocp.m, examples/acados_matlab_octave/getting_started/minimal_example_closed_loop.m, examples/acados_matlab_octave/getting_started/minimal_example_ocp.m, interfaces/acados_matlab_octave/detect_constraint_structure.m
The closed-loop example was returning non-zero status (`ACADOS_MAXITER`) so I changed the solver settings.
Also made the printing in `detect_constraint_structure` slightly more understandable.
=> MATLAB: add solver status checks to `getting_started` examples

acados/ocp_nlp/ocp_nlp_common.c, acados/ocp_nlp/ocp_nlp_common.h, acados/ocp_nlp/ocp_nlp_ddp.c, acados/ocp_nlp/ocp_nlp_ddp.h, acados/ocp_nlp/ocp_nlp_globalization_fixed_step.c, acados/ocp_nlp/ocp_nlp_globalization_funnel.c, acados/ocp_nlp/ocp_nlp_globalization_merit_backtracking.c
The `config->step_update` takes `qp_out` as input such that it is more modular. This enables Second-Order Corrections to use the same function for a step update while using different data structures to store the data.
=> Added `qp_out` as function input to `config->step_update`

interfaces/acados_matlab_octave/AcadosOcp.m, interfaces/acados_matlab_octave/AcadosOcpOptions.m, interfaces/acados_template/acados_template/acados_ocp.py, interfaces/acados_template/acados_template/acados_ocp_options.py
The default alpha reduction factor was changed. The `FUNNEL_L1PEN_LINESEARCH` method used `0.5` and the `MERIT_BACKTRACKING` used `0.7`. Now both methods use `0.7` and it works very well for the funnel.
=> Change of default `globalization_alpha_reduction` factor

examples/acados_python/p_global_example/example_p_global.py, examples/acados_python/pendulum_on_cart/as_rti/as_rti_closed_loop_example.py, examples/acados_python/pendulum_on_cart/custom_update/example_custom_rti_loop.py, examples/acados_python/pendulum_on_cart/ocp/example_sqp_rti_loop.py, examples/acados_python/pendulum_on_cart/ros2/example_ros_minimal_ocp.py, examples/acados_python/tests/test_rti_sqp_residuals.py, interfaces/acados_template/acados_template/acados_ocp_solver.py, interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx
- add warning for AS-RTI, as recomputing residual breaks the reuse of the linearization which is essential for AS-RTI to work correctly.
- test AS-RTI with `get_residuals()`
=> `AcadosOcpSolver.get_residuals()`: change default to `recompute=False`, fixes AS-RTI, breaking!
