acados/acados

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_gn_sqp.c
acados/ocp_nlp/ocp_nlp_gn_sqp.h
examples/test_chain.c
examples/test_ocp_qp_condensing_qpoases.c
experimental/dimitris/test_chain_mod.cpp
test/ocp_nlp/chain/test_chain.cpp

> moved maxIter from input to arguments 
> replaced create_workspace by calculate_workspace_size + cast
> fixed seg faults in some examples

Cleaning up nlp solver interface

---

acados/ocp_qp/ocp_qp_hpmpc.c

Cleaned up hpmpc interface. Need to double check that partial tightening is actually working.

Polishing hpmpc interface (need to debug partial tightening)

---

acados/ocp_qp/ocp_qp_common.c
acados/ocp_qp/ocp_qp_condensing_hpipm.c
acados/ocp_qp/ocp_qp_condensing_hpipm.h
acados/ocp_qp/ocp_qp_condensing_qpoases.c
acados/ocp_qp/ocp_qp_condensing_qpoases.h
acados/ocp_qp/ocp_qp_hpipm.c
acados/ocp_qp/ocp_qp_hpipm.h
examples/c/chen_nmpc_qpoases.c
examples/c/mass_spring_condensing_hpipm.c
examples/c/mass_spring_hpipm.c
examples/c/mass_spring_qpoases.c
examples/c/nonlinear_chain_sqp.c
test/ocp_qp/test_qpsolvers.cpp

It still gives segfault on ocp_nlp_py example.

Updated HPIPM and BLASFEO

---

swig/acados.i

fix casadi code generation (issue 162)

---

acados/dense_qp/dense_qp_common.c
acados/dense_qp/dense_qp_common.h
acados/dense_qp/dense_qp_qore.c
acados/dense_qp/dense_qp_qore.h
acados/dense_qp/dense_qp_qpoases.c
acados/dense_qp/dense_qp_qpoases.h
acados/ocp_qp/ocp_qp_common.c
acados/ocp_qp/ocp_qp_common.h
acados/ocp_qp/ocp_qp_common_frontend.c
acados/ocp_qp/ocp_qp_common_frontend.h
acados/ocp_qp/ocp_qp_condensing_solver.c
acados/ocp_qp/ocp_qp_partial_condensing.h
acados/ocp_qp/ocp_qp_sparse_solver.c
acados/utils/create.c
acados/utils/create.h
acados/utils/print.c
examples/c/mass_spring_condensing_hpipm.c
examples/c/mass_spring_condensing_qore.c
examples/c/mass_spring_condensing_qpoases.c
examples/c/mass_spring_hpipm.c
examples/c/mass_spring_pcond_hpipm_split.c

- added computation of KKT residiuals for dense/OCP QP
- implemented workspace allocation/casting in condensing/sparse solvers
- added create functions for dense/OCP QP residuals and their respective workspaces
- updated mass spring examples for QORE and qpOASES

KKT residuals

---

acados/dense_qp/dense_qp_common.h
acados/dense_qp/dense_qp_hpipm.c
acados/dense_qp/dense_qp_qore.c
acados/dense_qp/dense_qp_qpoases.c
acados/ocp_qp/ocp_qp_common.h
acados/ocp_qp/ocp_qp_condensing_solver.c
acados/ocp_qp/ocp_qp_hpipm.c
acados/ocp_qp/ocp_qp_qpdunes.c
acados/ocp_qp/ocp_qp_sparse_solver.c
acados/utils/mem.c
acados/utils/print.c
examples/c/mass_spring_cond_solver.c
examples/c/mass_spring_condensing_hpipm.c
examples/c/mass_spring_condensing_qore.c
examples/c/mass_spring_condensing_qpoases.c
examples/c/mass_spring_pcond_solver.c
examples/c/mass_spring_qpdunes.c

Also some small experiments with qpDUNES interface (see issue #188 )

Adds a number of iterations of a QP solver to qp_out

---

Makefile
Makefile.rule
acados/dense_qp/Makefile
acados/ocp_qp/Makefile
acados/ocp_qp/ocp_qp_qpdunes.c
examples/c/Makefile
examples/c/mass_spring_example.c
interfaces/acados_c/dense_qp.c
interfaces/acados_c/ocp_qp.c

Minor changes to make consistent with CMAKE pending

can include/exclude qpDUNES and qore from Makefile

---

acados/sim/sim_common.h
acados/sim/sim_erk_integrator.c
acados/sim/sim_erk_integrator.h
examples/c/nonlinear_chain_ocp_nlp.c
interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_c/ocp_nlp_interface.h
interfaces/acados_c/sim_interface.c
interfaces/acados_c/sim_interface.h

- cleaned up external functions using c interface
- added setters for (currently only explicit) functions in nlp in

Further nonlinear_chain example clean up and nlp interface extension

---

acados/sim/sim_erk_integrator.c
examples/c/CMakeLists.txt
examples/c/Makefile
examples/c/nonlinear_chain_ocp_nlp.c
examples/c/pendulum_scqp.cpp
examples/c/wind_turbine_nmpc.c

- added constraints on last stage
- fixed minor bug in constraints
- fixed linked files in cmake
TODO
- fix weird error with different behaviour between cmake and make on the same example..

polishing wind_turbine_nmpc example

---

acados/dense_qp/dense_qp_qore.c
acados/dense_qp/dense_qp_qpoases.c
acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_constraints.c
acados/ocp_nlp/ocp_nlp_constraints.h
acados/ocp_nlp/ocp_nlp_cost_common.h
acados/ocp_nlp/ocp_nlp_cost_external.c
acados/ocp_nlp/ocp_nlp_cost_external.h
acados/ocp_nlp/ocp_nlp_cost_ls.c
acados/ocp_nlp/ocp_nlp_cost_ls.h
acados/ocp_nlp/ocp_nlp_cost_nls.c
acados/ocp_nlp/ocp_nlp_cost_nls.h
acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_qp/ocp_qp_hpipm.c
acados/ocp_qp/ocp_qp_hpmpc.c
acados/ocp_qp/ocp_qp_qpdunes.c
acados/utils/print.c
examples/c/Makefile
examples/c/mass_spring_example.c
examples/c/mass_spring_model/mass_spring_qp.c
examples/c/mass_spring_nmpc_example.c
examples/c/nonlinear_chain_ocp_nlp.c
examples/c/nonlinear_chain_ocp_nlp_no_interface.c
examples/c/wind_turbine_nmpc.c

changes so far:
- added QP example (mass spring)
- checked HPIPM interface (it works)
- made the other QPs return FAILURE instead of seg-faulting

soft constraints (WIP)

---

acados/dense_qp/dense_qp_qpoases.c

Quickfix qpoases

---

examples/c/CMakeLists.txt
examples/c/implicit_chain_model/chain_mass_impl.m
examples/c/nonlinear_chain_ocp_nlp.c

fixed nonlinear_chain_ocp_nlp
updated select_dynamics casadi - removed unnecessary impl_ode funs
erk4_casadi was commented for some reason for masses 4 and 5
improved generating matlab file

Fix nonlinear chain ocp nlp

---

examples/matlab/ocp_nlp_example.m
interfaces/acados_c/options_interface.c
interfaces/acados_cpp/ocp_nlp/ocp_nlp.cpp

use RTI instead of SQP

---

experimental/tobi/swig_c/README.md
experimental/tobi/swig_c/acados.i
experimental/tobi/swig_c/swig_c_integrator.m
experimental/tobi/swig_c/swig_c_interface.m

I created this branch to evaluate the effort of creating a swig interface for acados_c interface. The result was very complex code in the high-level language. Because the concurrently developed MEX approach seemed easier at the time of writing this, this approach was abandoned.

experimental code to test SWIG wrapper for acados_c interface

---

acados/ocp_nlp/ocp_nlp_constraints_bgh.c

swap nbu for nu in setter for idxbx

fix setter for idxbx

---

acados/sim/sim_gnsf.c
acados/sim/sim_gnsf.h
interfaces/matlab/external_function_generation/sim/TEMPLATE_transcribe_model_into_gnsf_and_export.m
interfaces/matlab/external_function_generation/sim/TEST_export_linear_test_problem.m
interfaces/matlab/external_function_generation/sim/check_reformulation.m
interfaces/matlab/external_function_generation/sim/determine_input_nonlinearity_function.m
interfaces/matlab/external_function_generation/sim/determine_trivial_gnsf_transcription.m
interfaces/matlab/external_function_generation/sim/reformulate_with_LOS.m
roadmap.md

Worked a bit on GNSF, to prepare it for Matlab interface.
Also, found the `roadmap.md`, maybe we can try to update it at some point.

GNSF detection & documentation

---

interfaces/acados_template/acados_template/__init__.py
interfaces/acados_template/acados_template/acados_ocp_nlp.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/generate_solver.py

adding minor fixes to template interface

renamed ocp_nlp_render_arguments to ocp_nlp_acados and fixed Tera templates

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_reg_common.c
acados/ocp_nlp/ocp_nlp_reg_common.h
acados/ocp_nlp/ocp_nlp_reg_convexify.c
acados/ocp_nlp/ocp_nlp_reg_convexify.h
acados/ocp_nlp/ocp_nlp_reg_mirror.c
acados/ocp_nlp/ocp_nlp_reg_noreg.c
acados/ocp_nlp/ocp_nlp_reg_project.c
acados/ocp_nlp/ocp_nlp_reg_project_reduc_hess.c
acados/ocp_nlp/ocp_nlp_reg_project_reduc_hess.h
acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_nlp/ocp_nlp_sqp.h
acados/ocp_nlp/ocp_nlp_sqp_rti.c
acados/ocp_nlp/ocp_nlp_sqp_rti.h
acados/ocp_qp/ocp_qp_common.c
examples/matlab_mex/linear_mass_spring_model/example_ocp.m
examples/matlab_mex/masses_chain_model/example_ocp.m
examples/matlab_mex/pendulum_on_cart_model/example_ocp.m
examples/matlab_mex/wind_turbine_nx6/example_ocp.m
interfaces/acados_matlab/acados_ocp.m
interfaces/acados_matlab/acados_ocp_opts.m
interfaces/acados_matlab/ocp_compile_mex.m
interfaces/acados_matlab/ocp_create.c
interfaces/acados_matlab/ocp_get.c

Work toward fixing convexification algorithm, for the case of shifting cost.
Active inequality constraints still not considered.

Fix convexification

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_constraints_bgh.c
acados/ocp_nlp/ocp_nlp_constraints_bghp.c
acados/ocp_nlp/ocp_nlp_constraints_common.h
acados/ocp_nlp/ocp_nlp_cost_common.h
acados/ocp_nlp/ocp_nlp_cost_external.c
acados/ocp_nlp/ocp_nlp_cost_external.h
acados/ocp_nlp/ocp_nlp_cost_ls.c
acados/ocp_nlp/ocp_nlp_cost_ls.h
acados/ocp_nlp/ocp_nlp_cost_nls.c
acados/ocp_nlp/ocp_nlp_cost_nls.h
interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_c/ocp_nlp_interface.h
interfaces/acados_template/acados_template/c_templates/acados_solver_sfun.in.c
interfaces/acados_template/acados_template/generate_solver.py
interfaces/acados_template/examples/python/pendulum_example/generate_c_code.py
interfaces/acados_template/examples/python/rel_sync_machine_example/generate_c_code.py

@giaf, in order to implement this, I have added a couple of things to the core and C interface, have a look ;)

adding (stage-wise) setter for y_ref both in Simulink and Python

---

docs/installation/index.md
docs/interfaces/index.md
examples/acados_template/python/pendulum_example/generate_c_code.py
examples/acados_template/python/soft_constraints/generate_c_code.py
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp_nlp.py
interfaces/acados_template/acados_template/c_templates/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates/main.in.c
interfaces/acados_template/acados_template/c_templates_tera/main.in.c

some left overs from some work I did for a user from my master branch adding support for general and nonlinear soft constraints (will help merging the interfaces)

adding general and nonlinear soft-constraints

---

examples/matlab_mex/README.md
examples/matlab_mex/acados_examples_env.m

* Setting up the environment variable on Windows with a Matlab script.
* Some documentation in the `README.md` on how to run examples on Windows.

Mex windows doc and env setup script

---

acados/ocp_nlp/ocp_nlp_constraints_bghp.c
interfaces/acados_template/acados_template/c_templates/acados_sim_solver.in.c
interfaces/acados_template/acados_template/generate_c_code_implicit_ode.py

implement missing setters in BGHP constraints and fix generated sim for implicit integrators

Quickfix templates

---

examples/acados_matlab_octave/swarming/env.sh
examples/acados_matlab_octave/swarming/example_closed_loop.m
examples/acados_matlab_octave/swarming/example_ocp.m
examples/acados_matlab_octave/swarming/example_sim.m
examples/acados_matlab_octave/swarming/swarming_model.m

This PR adds the swarming example. Differently from the previous PR, I started from the updated master branch and integrated the comments of the previous PR.
Sorry for opening the previous!
Enrica

Added swarming example

---

acados/ocp_nlp/ocp_nlp_constraints_bghp.c
acados/ocp_nlp/ocp_nlp_cost_ls.c
acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_nlp/ocp_nlp_sqp_rti.c
acados/ocp_qp/ocp_qp_full_condensing.c
acados/sim/sim_common.c
examples/acados_matlab_octave/pendulum_on_cart_model/minimal_example_ocp.m
examples/acados_matlab_octave/pendulum_on_cart_model/minimal_example_sim.m
examples/acados_matlab_octave/test/test_sens_forw.m
examples/c/no_interface_examples/mass_spring_example.c
interfaces/acados_matlab_octave/mex_macros.h
interfaces/acados_matlab_octave/ocp_create.c
interfaces/acados_matlab_octave/ocp_get.c
interfaces/acados_matlab_octave/ocp_set.c
interfaces/acados_matlab_octave/sim_create.c
interfaces/acados_matlab_octave/sim_get.c
interfaces/acados_matlab_octave/sim_set.c
test/sim/sim_test_ode.cpp

- Fix compiler warnings
- Mex: improve error messages, fix some possibilities to crash Matlab

Present the mex interface

---

interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/generate_solver_matlab.m

@FreyJo this should fix the problem with code-gen from MATLAB ;)

add code-gen for sim_solver

---

acados/ocp_nlp/ocp_nlp_constraints_bghp.c
examples/acados_template/python/rel_sync_machine_example/generate_c_code.py
examples/acados_template/python/soft_constraints/generate_c_code.py
interfaces/acados_template/acados_template/c_templates/acados_sim_solver.in.c
interfaces/acados_template/acados_template/c_templates/acados_sim_solver.in.h
interfaces/acados_template/acados_template/c_templates/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates/acados_solver_sfun.in.c
interfaces/acados_template/acados_template/c_templates/main.in.c
interfaces/acados_template/acados_template/casadi_functions.py
interfaces/acados_template/acados_template/generate_c_code_constraint.py
interfaces/acados_template/acados_template/generate_c_code_constraint_e.py
interfaces/acados_template/acados_template/generate_c_code_explicit_ode.py
interfaces/acados_template/acados_template/generate_c_code_implicit_ode.py

Python CasADi code-gen + Jinja only (I think @FreyJo is implementing this for Tera already).

Using parametric CasADi functions by default in templates

---

interfaces/acados_matlab_octave/sim_check_dims.m

MEX: sim_check_dims, fix for empty casadi expressions

---

interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

The first one was introduced recently, how did it not break the tests?

fixing bugs in acados_solver.in.c - C_e not set, wrong D and C dims

---

interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/acados_solver_sfun.in.c

Global data should only be defined ones either in the main and in the S-Function OR in the solver.

fix bug in S-Function

---

acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_nlp/ocp_nlp_sqp.h
acados/ocp_nlp/ocp_nlp_sqp_rti.c
acados/ocp_nlp/ocp_nlp_sqp_rti.h
examples/acados_python/getting_started/minimal_example_ocp.py
examples/acados_python/pmsm_example/generate_c_code.py
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_config_json.m
interfaces/acados_template/acados_template/AcadosOcp.py
interfaces/acados_template/acados_template/AcadosOcpSolver.py
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

1. adding print_level option
2. add opts_set setter to Python interface
3. changing to shorter setter name cons_set in Python interface

add print_level option

---

CMakeLists.txt

This should fix the cmake installation with OSQP
https://github.com/acados/acados/issues/562

Fix the cmake installation with OSQP

---

examples/acados_matlab_octave/test/test_ocp_wtnx6.m
interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_matlab_octave/ocp_set.c
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h

3 minor fixes that don't really need a review.

Quick fixes

---

examples/acados_matlab_octave/test/test_ocp_linear_mass_spring.m
interfaces/acados_matlab_octave/ocp_create.c

Reported as broken in the forum:
https://discourse.acados.org/t/configuration-of-the-numerical-simulation-method/132

Mex discrete dynamics: fix and add test

---

acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_constraints_bgh.c
acados/ocp_nlp/ocp_nlp_cost_ls.c
docs/Makefile
docs/interfaces/index.md
examples/acados_python/getting_started/ocp/nonuniform_discretization_example.py
interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_constraints_json.m
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_dims_json.m
interfaces/acados_matlab_octave/detect_dims_ocp.m
interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/main.in.c
interfaces/acados_template/acados_template/c_templates_tera/mex_solver.in.m

Replacing:
https://github.com/acados/acados/pull/579
Additionally includes some setters/getters and documentation.

Python: detect x0, fix doxygen

---

interfaces/acados_matlab_octave/detect_dims_ocp.m

Ooops, thanks for spotting
https://discourse.acados.org/t/time-optimal-formulation/56/11

mex: add missing 'end'

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
interfaces/acados_matlab_octave/acados_ocp_opts.m
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_options_json.m
interfaces/acados_matlab_octave/ocp_create.c
interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

Only the last commit is not included in #573 
https://github.com/acados/acados/pull/574/commits/2d6ecebd954161533f8560fd5cebdfd8a15cb1f2

Levenberg Marquardt Regularization term

---

interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h

https://discourse.acados.org/t/problem-with-parameters-in-cost-with-nonlinear-ls/141

Quick fix nls param

---

interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

Removing the dimension checks complete was a bit to much, 44cf6df0.
However, doing one generic check is sufficient and readable.

templates: add generic dimension check to acados_update_params

---

acados/ocp_nlp/ocp_nlp_cost_external.c
acados/ocp_nlp/ocp_nlp_cost_external.h
examples/acados_python/getting_started/ocp/ocp_example_cost_formulations.py
interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_options_json.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/Makefile.in
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/external_cost.in.h
interfaces/acados_template/acados_template/c_templates_tera/external_cost_e.in.h
interfaces/acados_template/acados_template/generate_c_code_external_cost.py

add option to use custom hessian approximation for external cost module

Add option to use numerical hessian approximation for contribution of external cost module

---

interfaces/acados_matlab_octave/ocp_create.c

https://discourse.acados.org/t/possible-error-for-cost-z-e-in-ocp-create-c/174

MEX: fix dimension check for terminal soft constraints

---

interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_matlab_octave/ocp_create.c

Replacing
https://github.com/acados/acados/pull/615

Matlab: try around ocp_create, missing dim check on y_ref

---

.travis.yml
examples/acados_matlab_octave/test/run_tests_ocp.m
examples/acados_matlab_octave/test/run_tests_sim.m
examples/acados_matlab_octave/test/run_tests_templates.m
interfaces/acados_template/acados_template/c_templates_tera/acados_mex_create.in.c

Hot fix for Matlab.
Fixed path error in Mex tests.
Found this bug, to be fixed later:
https://github.com/acados/acados/issues/625

Mex test hotfix

---

examples/acados_python/race_cars/acados_settings.py
examples/acados_python/race_cars/acados_settings_dev.py
examples/acados_python/race_cars/bycicle_model.py
examples/acados_python/race_cars/main.py

Changed some settings in the race car example.
Use new file, to keep the settings file match the settings in the publication.
https://cdn.syscop.de/publications/Kloeser2020.pdf

Race cars july2020

---

interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py

Related to this https://discourse.acados.org/t/unable-to-provide-initial-condition-to-specific-states/247

Python: set nbxe_0 only if x0 is set

---

interfaces/acados_template/acados_template/acados_ocp_solver.py

https://discourse.acados.org/t/unable-to-provide-initial-condition-to-specific-states/247/3

Python: set nbxe_0 only if x0 is set - include idxbxe_0 in check

---

interfaces/acados_template/acados_template/generate_c_code_constraint.py
interfaces/acados_template/acados_template/generate_c_code_discrete_dynamics.py
interfaces/acados_template/acados_template/generate_c_code_explicit_ode.py
interfaces/acados_template/acados_template/generate_c_code_external_cost.py
interfaces/acados_template/acados_template/generate_c_code_gnsf.py
interfaces/acados_template/acados_template/generate_c_code_implicit_ode.py
interfaces/acados_template/acados_template/generate_c_code_nls_cost.py
interfaces/acados_template/acados_template/utils.py

While playing around with acados,
there was sometimes an incorrect inference of SX/MX.
Proposed fix is probably not complete, but at least it covered the cases I encountered

avoid SX/MX confusion

---

acados/ocp_nlp/ocp_nlp_cost_ls.c

C: cost_ls: fix bug in compute_fun for `nz > 0`
- recompute `Cyt_tilde` in `compute_fun`
- avoid copying `y_ref, Cyt` in `compute_fun` and `update_qp_matrices`

C: cost_ls: fix bug in compute_fun by recomputing Cyt_tilde, avoid copying y_ref, Cyt

---

interfaces/acados_template/acados_template/c_templates_tera/main_sim.in.c

Exposed by 53e06fd90ea706dda5a17bd7b0bd30f6a80c86d7

Python: sim -- don't assume lbx_0 is of length nx and ordered

---

acados/sim/sim_common.c
examples/acados_python/getting_started/common/pendulum_model.py
examples/acados_python/getting_started/mhe/closed_loop_mhe_ocp.py
examples/acados_python/getting_started/mhe/minimal_example_mhe.py
examples/acados_python/getting_started/mhe/minimal_example_mhe_with_noisy_param.py
examples/acados_python/getting_started/mhe/minimal_example_mhe_with_param.py
examples/acados_python/getting_started/minimal_example_closed_loop.py
examples/acados_python/getting_started/ocp/example_ocp_dynamics_formulations.py
examples/acados_python/getting_started/ocp/example_sqp_qpDUNES.py
examples/acados_python/getting_started/ocp/example_sqp_rti_loop.py
examples/acados_python/getting_started/ocp/minimal_example_ocp.py
examples/acados_python/getting_started/ocp/nonuniform_discretization_example.py
examples/acados_python/getting_started/ocp/ocp_example_cost_formulations.py
examples/acados_python/getting_started/sim/extensive_example_sim.py
examples/acados_python/getting_started/sim/minimal_example_sim.py
examples/acados_python/tests/soft_constraint_test.py
examples/acados_python/tests/test_ocp_setting.py
examples/acados_python/tests/test_osqp.py
examples/acados_python/tests/test_parametric_nonlinear_constraint_h.py
examples/acados_python/tests/test_sim_dae.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_sim_solver.py

Addressing these topics from the forum:
https://discourse.acados.org/t/getting-z-from-acadossimsolver/301
https://discourse.acados.org/t/modifying-solver-tolerance-after-solver-creation/304

Python: Integrator DAE support + Update OCP solver tolerances

---

examples/acados_matlab_octave/test/run_test_template_ocp_disc_dyn.m
examples/acados_matlab_octave/test/run_test_template_ocp_linear_dae.m
examples/acados_matlab_octave/test/run_test_template_ocp_pendulum_auto.m
examples/acados_matlab_octave/test/run_test_template_ocp_pendulum_exact_hess.m
examples/acados_matlab_octave/test/run_test_template_ocp_pendulum_ext_cost.m
examples/acados_matlab_octave/test/run_test_template_ocp_pendulum_gnsf.m
examples/acados_matlab_octave/test/run_test_template_ocp_pendulum_nls.m
examples/acados_matlab_octave/test/test_template_pendulum_ocp.m
interfaces/CMakeLists.txt

Octave template tests were failing irregularly without proper error.
https://github.com/acados/acados/pull/670

Tests: run octave template tests separately

---

interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/acados_mex_create.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_mex_free.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_mex_solve.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/acados_solver_sfun.in.c
interfaces/acados_template/acados_template/c_templates_tera/main.in.c
interfaces/acados_template/acados_template/c_templates_tera/main_mex.in.c
interfaces/acados_template/acados_template/c_templates_tera/mex_solver.in.m

https://discourse.acados.org/t/thread-safe-version/123

Thread safe templates

---

interfaces/acados_template/acados_template/acados_ocp_solver.py

Fixes segfaults on my linux system

Python: fixing some regression introduced in 2ce6e65d4

---

examples/acados_matlab_octave/pendulum_on_cart_model/pendulum_on_cart_model_with_param.m
examples/acados_matlab_octave/test/Makefile
examples/acados_matlab_octave/test/test_template_pendulum_exact_hess.m
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/render_acados_templates.m
interfaces/acados_matlab_octave/ocp_set.c
interfaces/acados_template/acados_template/c_templates_tera/acados_mex_create.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_mex_set.in.c
interfaces/acados_template/acados_template/c_templates_tera/make_mex.in.m
interfaces/acados_template/acados_template/c_templates_tera/mex_solver.in.m

- Added test to reproduce the bug reported here https://discourse.acados.org/t/segmentation-violation-in-matlab-using-template-interface/375
- Made templated version of ocp_set that calls `{{ model.name }}_acados_update_params` for the proper paramter update.
- minor formatting

Hot fix: template based MEX OCP solver parameter interaction

---

examples/acados_matlab_octave/generic_external_cost/env.sh
examples/acados_matlab_octave/generic_external_cost/external_cost_example_ocp.m
examples/acados_matlab_octave/generic_external_cost/generic_ext_cost.c
interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_matlab_octave/acados_ocp_model.m
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_cost_json.m
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/render_acados_templates.m
interfaces/acados_matlab_octave/generate_c_code_ext_cost.m
interfaces/acados_matlab_octave/ocp_destroy_ext_fun.c
interfaces/acados_matlab_octave/ocp_generate_casadi_ext_fun.m
interfaces/acados_matlab_octave/ocp_set.c
interfaces/acados_matlab_octave/ocp_set_ext_fun.m
interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/Makefile.in
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/mex_solver.in.m

Replacing https://github.com/acados/acados/pull/703

Added support for generic external cost functions in template based interface + Matlab

---

examples/acados_matlab_octave/getting_started/extensive_example_ocp.m
examples/acados_matlab_octave/test/test_template_pendulum_exact_hess.m
examples/acados_python/getting_started/ocp/nonuniform_discretization_example.py
interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

Add varying integrator settings in template based interface

---

examples/acados_matlab_octave/test/test_ocp_linear_mass_spring.m
interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_matlab_octave/mex_macros.h
interfaces/acados_matlab_octave/ocp_get.c
interfaces/acados_matlab_octave/ocp_set.c

load_iterate and store_iterate for Matlab and extensions to matlab interface getters and setters

load_iterate and store_iterate for Matlab

---

CMakeLists.txt
docs/installation/index.md
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/compile_main.m
interfaces/acados_matlab_octave/ocp_compile_interface.m
interfaces/acados_matlab_octave/ocp_generate_casadi_ext_fun.m
interfaces/acados_matlab_octave/ocp_set_ext_fun.m
interfaces/acados_matlab_octave/sim_compile_interface.m
interfaces/acados_matlab_octave/sim_generate_casadi_ext_fun.m
interfaces/acados_matlab_octave/sim_set_ext_fun.m
interfaces/acados_template/acados_template/c_templates_tera/make_sfun.in.m

Replacing https://github.com/acados/acados/pull/719 rebased on `master` branch because there were conflicts after merging https://github.com/acados/acados/pull/717
Added some documentation on MSVC, see last commit.

Matlab: support for Microsoft Visual C Compiler (MVSC)

---

examples/acados_matlab_octave/test/test_template_pendulum_exact_hess.m
interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_matlab_octave/acados_ocp_opts.m
interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m

Meant to be merged instead of
https://github.com/acados/acados/pull/724

Mex template parameters

---

interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

This is the follow-up of PR  #726
The original was not granular enough and had still some bugs.

Acados solver code generation improvements

---

interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m

Bugfix for assigning the IDs of slack for Terminal stage.

Bugfix: J to idx slacks for terminal stage

---

examples/acados_matlab_octave/pendulum_on_cart_model/example_ocp_custom_hess.m
examples/acados_python/getting_started/ocp/example_custom_hessian.py
interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_matlab_octave/acados_ocp_model.m
interfaces/acados_matlab_octave/generate_c_code_ext_cost.m
interfaces/acados_template/acados_template/acados_model.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/generate_c_code_external_cost.py

 custom hessian for external cost

---

examples/acados_matlab_octave/test/run_test_template_lin_mass_ocp.m
examples/acados_matlab_octave/test/test_template_lin_mass_ocp.m
interfaces/CMakeLists.txt
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/acados_model_json.m
interfaces/acados_matlab_octave/ocp_generate_c_code.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_model.py
interfaces/acados_template/acados_template/c_templates_tera/Makefile.in
interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_sim_solver_sfun.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver_sfun.in.c
interfaces/acados_template/acados_template/utils.py

- addresses: https://discourse.acados.org/t/error-generation-of-makefile-when-using-gnsf/588/2
- minor: comment includes as suggested here https://discourse.acados.org/t/error-generation-of-makefile-when-using-gnsf/588/2

Template interfaces work with degenerated GNSF models

---

acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_nlp/ocp_nlp_sqp.h
acados/ocp_nlp/ocp_nlp_sqp_rti.c
acados/ocp_nlp/ocp_nlp_sqp_rti.h
examples/acados_matlab_octave/getting_started/extensive_example_ocp.m
examples/acados_matlab_octave/getting_started/minimal_example_closed_loop.m
examples/acados_matlab_octave/pendulum_on_cart_model/example_ocp_param_sens.m
examples/acados_matlab_octave/pendulum_on_cart_model/example_solution_sens_closed_loop.m
examples/acados_python/getting_started/example_solution_sens_closed_loop.py
examples/acados_python/getting_started/minimal_example_closed_loop.py
interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h

- interfacing for Matlab and Python
- examples

Work on sensitivities of OCP solution

---

examples/acados_matlab_octave/generic_external_cost/external_cost_example_ocp.m
examples/acados_python/crane/time_optimal_example.py
interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m
interfaces/acados_template/acados_template/c_templates_tera/main.in.c

See https://discourse.acados.org/t/proper-setting-of-the-initial-guess/677

Minor fixes - acados forum responses

---

docs/installation/index.md
docs/list_of_projects/index.md

reminder to myself to build and upload docs before merging

Documentation updates

---

examples/acados_python/crane/time_optimal_example.py
interfaces/acados_matlab_octave/ocp_generate_c_code.m
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver_sfun.in.c

- Addressed https://discourse.acados.org/t/acados-makefile-error-on-windows-for-simulink-example-m/712
The Makefile main target for Windows seems to have https://github.com/acados/acados/pull/781

[WIP] Minor changes

---

examples/acados_python/getting_started/example_solution_sens_closed_loop.py
examples/acados_python/getting_started/mhe/closed_loop_mhe_ocp.py
examples/acados_python/getting_started/mhe/minimal_example_mhe.py
examples/acados_python/getting_started/mhe/minimal_example_mhe_with_noisy_param.py
examples/acados_python/getting_started/mhe/minimal_example_mhe_with_param.py
examples/acados_python/getting_started/minimal_example_closed_loop.py
examples/acados_python/getting_started/ocp/example_custom_hessian.py
examples/acados_python/getting_started/ocp/example_ocp_dynamics_formulations.py
examples/acados_python/getting_started/ocp/minimal_example_ocp_cmake.py
examples/acados_python/getting_started/ocp/minimal_example_ocp_reuse_code.py
examples/acados_python/getting_started/ocp/nonuniform_discretization_example.py
examples/acados_python/getting_started/ocp/ocp_example_cost_formulations.py
examples/acados_python/getting_started/sim/extensive_example_sim.py
examples/acados_python/getting_started/sim/minimal_example_sim.py
examples/acados_python/getting_started/sim/minimal_example_sim_cmake.py
interfaces/acados_template/acados_template/builders.py
interfaces/acados_template/acados_template/utils.py

https://discourse.acados.org/t/problems-when-running-minimal-example-closed-loop-py/726

Python3.5 compatiblity

---

acados/dense_qp/dense_qp_hpipm.c
acados/ocp_qp/ocp_qp_hpipm.c
examples/acados_python/getting_started/ocp/nonuniform_discretization_example.py
examples/acados_python/tests/test_cython_ctypes.py
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_options_json.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

Interface HPIPM opts in C and Python
Plus minor changes
https://github.com/acados/acados/issues/801

Interface HPIPM opts

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_sqp.c
examples/acados_python/README.md
examples/acados_python/linear_mass_model/linear_mass_test_problem.py
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/ocp_nlp_solver_options_json.m
interfaces/acados_matlab_octave/set_up_acados_ocp_nlp_json.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx
interfaces/acados_template/acados_template/acados_sim.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/mex_solver.in.m
interfaces/acados_template/acados_template/generate_c_code_explicit_ode.py
interfaces/acados_template/acados_template/utils.py

Looked into
https://discourse.acados.org/t/different-behavior-in-acados-ocp-and-code-generation/639/2

Some interface improvements

---

docs/installation/index.md
interfaces/acados_c/ocp_nlp_interface.h

Looked into this:
https://discourse.acados.org/t/runtime-errors-with-msvc-not-with-mingw/728

Minor changes for MSVC

---

ROADMAP.md
acados/ocp_nlp/ocp_nlp_sqp.c
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/acados_ocp_nlp_json.m
interfaces/acados_matlab_octave/ocp_generate_c_code.m
interfaces/acados_template/acados_template/acados_layout.json
interfaces/acados_template/acados_template/acados_ocp_solver.py

* ROADMAP minor update
* add json_file to layout
* C: SQP: add qp_iter to print_level table
* Python: readd acados_ocp to acados_ocp_solver

Improve C print_level, Python minor changes

---

acados/utils/external_function_generic.c
examples/acados_python/tests/test_parametric_nonlinear_constraint_h.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.pxd

Replacing https://github.com/acados/acados/pull/600

Partial param update 2022

---

acados/ocp_nlp/ocp_nlp_common.c
acados/sim/sim_collocation_utils.c
acados/sim/sim_common.c
acados/sim/sim_irk_integrator.c
acados/sim/sim_lifted_irk_integrator.c
acados/utils/external_function_generic.c

Following https://docs.acados.org/developer_guide/index.html

Double checked some memory alignments

---

acados/sim/sim_gnsf.c
examples/acados_python/chain_mass/minimal_example_sim.py
examples/acados_python/getting_started/sim/extensive_example_sim.py
interfaces/acados_matlab_octave/detect_gnsf_structure.m
interfaces/acados_matlab_octave/gnsf/check_reformulation.m
interfaces/acados_matlab_octave/gnsf/determine_input_nonlinearity_function.m
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_sim_solver.py
interfaces/acados_template/acados_template/gnsf/check_reformulation.py
interfaces/acados_template/acados_template/gnsf/detect_affine_terms_reduce_nonlinearity.py
interfaces/acados_template/acados_template/gnsf/detect_gnsf_structure.py
interfaces/acados_template/acados_template/gnsf/determine_input_nonlinearity_function.py
interfaces/acados_template/acados_template/gnsf/determine_trivial_gnsf_transcription.py
interfaces/acados_template/acados_template/gnsf/matlab to python.md
interfaces/acados_template/acados_template/gnsf/reformulate_with_LOS.py
interfaces/acados_template/acados_template/gnsf/reformulate_with_invertible_E_mat.py
interfaces/acados_template/acados_template/gnsf/structure_detection_print_summary.py
interfaces/acados_template/acados_template/utils.py

Translated the GNSF structure detection from Matlab to Python.

GNSF detection in Python

---

docs/installation/index.md
docs/python_interface/index.md
interfaces/acados_template/setup.py

added Windows 10+ WSL installation instructions along with instructions for the python interface, removed version constraint in the python interface setup

added Windows 10+ WSL installation instructions

---

interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

Fixed wrong indexing of C_e matrix in template-based interface.

Template interface: fix C_e wrong indexing

---

examples/acados_python/Unicycle/main.py
examples/acados_python/Unicycle/robot_model.py
examples/acados_python/Unicycle/utils.py

Unicycle example added

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_cost_common.h
acados/ocp_nlp/ocp_nlp_cost_conl.c
acados/ocp_nlp/ocp_nlp_cost_conl.h
acados/ocp_nlp/ocp_nlp_cost_external.c
acados/ocp_nlp/ocp_nlp_cost_external.h
acados/ocp_nlp/ocp_nlp_cost_ls.c
acados/ocp_nlp/ocp_nlp_cost_ls.h
acados/ocp_nlp/ocp_nlp_cost_nls.c
acados/ocp_nlp/ocp_nlp_cost_nls.h
acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_nlp/ocp_nlp_sqp_rti.c
examples/acados_python/getting_started/ocp/ocp_example_cost_formulations.py

* add `precompute` to all cost modules
* `LINEAR_LS`: recompute `W_chol` only if `W` has changed, recompute cost Hessian if `Cyt` or `scaling` have changed
* `NONLINEAR_LS`: recompute `W_chol` only if `W` has changed

Computation of W_chol (W_chol + Hessian) in nonlinear LS (linear LS) only if data changes

---

examples/acados_python/getting_started/cython_example_closed_loop.py
examples/acados_python/getting_started/minimal_example_closed_loop.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx
interfaces/acados_template/acados_template/acados_sim_solver.py
interfaces/acados_template/acados_template/acados_sim_solver_pyx.pyx

Simple wrapper around `solve()` for `AcadosOcpSolver` and `AcadosSimSolver`

Wrapper around solve() for ocp solver and simulator

---

examples/acados_python/pendulum_on_cart/custom_update/README.md
examples/acados_python/pendulum_on_cart/custom_update/custom_update_function.c
examples/acados_python/pendulum_on_cart/custom_update/custom_update_function.h
examples/acados_python/pendulum_on_cart/custom_update/example_custom_rti_loop.py
examples/acados_python/pendulum_on_cart/ocp/example_sqp_rti_loop.py
examples/acados_python/pendulum_on_cart/ocp/nonuniform_discretization_example.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/Makefile.in
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h

Custom C function to update solver data and parameters in between solver calls efficiently.
Example is provided.
All fields `custom_update*` are documented with Python docstrings.

Add option to use a custom update function in Template workflow, can be called between OCP solver calls

---

examples/acados_python/pendulum_on_cart/custom_update/custom_update_function.c
examples/acados_python/pendulum_on_cart/custom_update/custom_update_function.h
examples/acados_python/pendulum_on_cart/custom_update/example_custom_rti_loop.py
examples/acados_python/pendulum_on_cart/ocp/example_sqp_rti_loop.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.pxd

Custom_update follow up: add data to update function and fix for Cython

---

acados/ocp_nlp/ocp_nlp_cost_external.c
acados/ocp_nlp/ocp_nlp_cost_external.h
examples/acados_python/pendulum_on_cart/ocp/ocp_example_cost_formulations.py
interfaces/acados_matlab_octave/generate_c_code_ext_cost.m
interfaces/acados_template/acados_template/generate_c_code_external_cost.py

The hessian is computed as
`H = d2l_dxu2 + dz_dux.T * d2l_dz2 * dz_dux + d2l_dux_dz * dz_dux + (d2l_dux_dz * dz_dux).T`
The term `d2z_dux2` is omitted!

Hessian for external cost with algebraic variables

---

examples/acados_python/pendulum_on_cart/ocp/minimal_example_ocp_cmake.py
interfaces/acados_template/acados_template/c_templates_tera/CMakeLists.in.txt

Closes https://github.com/acados/acados/issues/904

Fix templated cmake and test it

---

examples/acados_matlab_octave/acados_env_variables_windows.m

see:
https://discourse.acados.org/t/acados-example-in-matlab/957/4
https://github.com/acados/acados/pull/897

Add acados_env_variables_windows.m in examples folder

---

examples/acados_python/pendulum_on_cart/ocp/simulink_example.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/__init__.py
interfaces/acados_template/acados_template/utils.py

As requested here:
https://discourse.acados.org/t/create-simulink-wrapper-from-python/1120/2

Example to create Simulink wrapper from Python

---

docs/problem_formulation/problem_formulation_ocp_mex.tex

Is this correct? Adding ^e to J_sbx here.

Update problem_formulation_ocp_mex.tex with J_sbx^e

---

examples/acados_python/Unicycle/utils.py
examples/acados_python/chain_mass/export_chain_mass_integrator.py
examples/acados_python/chain_mass/run_nominal_control.py
examples/acados_python/chain_mass/utils.py
examples/acados_python/cstr/cstr_utils.py
examples/acados_python/cstr/integrator_experiment.py
examples/acados_python/getting_started/utils.py
examples/acados_python/linear_mass_model/linear_mass_model.py
examples/acados_python/pendulum_on_cart/common/utils.py
examples/acados_python/pendulum_on_cart/mhe/minimal_example_mhe.py
examples/acados_python/pendulum_on_cart/mhe/minimal_example_mhe_with_noisy_param.py
examples/acados_python/pendulum_on_cart/mhe/minimal_example_mhe_with_param.py
examples/acados_python/pendulum_on_cart/ocp/example_custom_hessian.py
examples/acados_python/pendulum_on_cart/ocp/example_sqp_rti_loop.py
examples/acados_python/pendulum_on_cart/ocp/minimal_example_ocp_cmake.py
examples/acados_python/pendulum_on_cart/ocp/minimal_example_ocp_reuse_code.py
examples/acados_python/pendulum_on_cart/ocp/simulink_example.py
examples/acados_python/pendulum_on_cart/sim/extensive_example_sim.py
examples/acados_python/pendulum_on_cart/sim/minimal_example_sim_cmake.py
examples/acados_python/rsm_example/main.py
examples/acados_python/rsm_example/plot_utils.py
examples/acados_python/tests/soft_constraint_test.py
examples/acados_python/tests/test_osqp.py
examples/acados_python/tests/test_sim_dae.py
examples/acados_python/zoRO_example/diff_drive/diff_drive_utils.py
interfaces/acados_template/acados_template/__init__.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_sim_solver.py
interfaces/acados_template/acados_template/plot_utils.py

- refactor RSM example
- add `latexify_plot` function to `acados_template`

Refactor examples

---

acados/ocp_nlp/ocp_nlp_common.c
examples/acados_python/pendulum_on_cart/ocp/example_optimal_cost_derivative.py
examples/acados_python/pendulum_on_cart/ocp/example_optimal_value_derivative.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py

* introduce new dimension `ns_0` - total number of slacks at the first stage
* get the gradient of the optimal value function w.r.t. the initial state `x0` via the multipliers

python interface: get the gradient of the optimal value function

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_cost_external.c
acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_nlp/ocp_nlp_sqp_rti.c
acados/ocp_qp/ocp_qp_xcond_solver.c
acados/sim/sim_irk_integrator.c
examples/c/no_interface_examples/mass_spring_nmpc_example.c
examples/c/no_interface_examples/nonlinear_chain_ocp_nlp_no_interface.c

Following what was found via https://github.com/acados/acados/pull/982

fix CodeQL warnings

---

examples/acados_matlab_octave/linear_mpc/README.md
examples/acados_matlab_octave/linear_mpc/env.sh
examples/acados_matlab_octave/linear_mpc/example_closed_loop.m
examples/acados_matlab_octave/linear_mpc/quadcopter.m

The example is based on quadcopter control and taken from [OSQP's website](https://osqp.org/docs/examples/mpc.html).

Add a linear MPC example in MATLAB

---

docs/algorithm_overview/index.md
docs/conf.py
docs/python_interface/index.md
docs/python_interface/py_acados_classes.dot
interfaces/acados_template/acados_template/acados_model.py
interfaces/acados_template/acados_template/acados_multiphase_ocp.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_sim.py

Fixed references, added multiphase OCP.
Docs from this PR are already uploaded to https://docs.acados.org/

Documentation: fixes and updates

---

examples/acados_python/multiphase_nonlinear_constraints/main.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c

Fixes https://discourse.acados.org/t/acados-multiphase-python-with-different-constraint-functions-per-phase/1401

Fix multiphase nonlinear constraints

---

interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/compile_ocp_shared_lib.m
interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/compile_sim_shared_lib.m
interfaces/acados_template/acados_template/c_templates_tera/CMakeLists.in.txt

https://discourse.acados.org/t/bug-with-visual-studio-compiler-in-matlab-with-working-fix/1449

fix Matlab with MSVC

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_dynamics_cont.c

- formatting: tabs to spaces
- move cost integration memory preparation to precompute

Minor C changes

---

interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_create.in.c
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/mex_solver.in.m

Closes https://github.com/acados/acados/issues/1049

Fix solution sensitivities in Matlab

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_sqp_rti.c
acados/ocp_qp/ocp_qp_hpipm.c
acados/ocp_qp/ocp_qp_partial_condensing.c
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx

* remove dead code
* replace utcnow with now
* get k from HPIPM
* move copy_ocp_nlp_out to common

Small cleanup

---

examples/acados_python/cstr/cstr_model.py
examples/acados_python/cstr/integrator_experiment.py
examples/acados_python/cstr/main.py
examples/acados_python/cstr/setup_acados_ocp_solver.py
examples/acados_python/getting_started/minimal_example_closed_loop.py
examples/acados_python/getting_started/minimal_example_ocp.py
examples/acados_python/getting_started/minimal_example_sim.py
examples/acados_python/getting_started/pendulum_model.py
examples/acados_python/getting_started/utils.py
examples/acados_python/zoRO_example/cstr/main.py
examples/acados_python/zoRO_example/cstr/zoro_ocp_solver.py
interfaces/acados_template/acados_template/acados_model.py
interfaces/acados_template/acados_template/acados_sim_solver.py

- add T to `AcadosSimSolver`
- AcadosModel: add time_label, ulabels, xlabels
- improve plot and demonstrate usage in getting started example
- improve CSTR example

Python convenience improvements

---

acados/CMakeLists.txt
cmake/acadosConfig.cmake.in

Although most of the issues with using acados in another cmake project (https://github.com/acados/acados/issues/1025) have been fixed with https://github.com/acados/acados/pull/1065, there are still a few lines missing in acadosConfig.cmake.in.

Fix acados cmake config

---

examples/acados_matlab_octave/getting_started/minimal_example_closed_loop.m
examples/acados_matlab_octave/getting_started/minimal_example_ocp.m
examples/acados_matlab_octave/pendulum_on_cart_model/pendulum_on_cart_model_with_param.m
examples/acados_python/getting_started/minimal_example_closed_loop.py
examples/acados_python/getting_started/minimal_example_ocp.py

Turn on globalization in all minimal examples.

Globalization in minimal examples

---

acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_nlp/ocp_nlp_sqp_rti.c
examples/acados_python/unicycle/main.py
interfaces/acados_template/acados_template/acados_model.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/casadi_function_generation.py
interfaces/acados_template/acados_template/mpc_utils.py
interfaces/acados_template/acados_template/penalty_utils.py
interfaces/acados_template/acados_template/utils.py

* cleanup python solver
* add MPC utils

Miscellaneous python improvements

---

interfaces/acados_template/acados_template/acados_sim_solver.py

Add if for `winmode`. Done already for OCP solver in #1006

AcadosSimSolver python 3.7 compatibility

---

acados/ocp_nlp/ocp_nlp_ddp.c
interfaces/acados_template/acados_template/acados_ocp.py

- some constraints were not removed properly
- add options `keep_cost`
See https://discourse.acados.org/t/ddp-reformulation-question/1580

improve `translate_to_feasibility_problem`

---

interfaces/acados_template/acados_template/acados_ocp_constraints.py
interfaces/acados_template/acados_template/utils.py

Solved the problem reported in https://discourse.acados.org/t/infeasible-qps-when-using-nonlinear-casadi-constraint-expressions/1595

Python: check if bounds are 1-dimensional numpy arrays

---

interfaces/acados_template/acados_template/acados_sim_batch_solver.py
interfaces/acados_template/acados_template/acados_sim_solver.py

fix missing openMP check

---

interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_sim_solver.py
interfaces/acados_template/acados_template/utils.py

* move check for openmp to separate function
* move loading of shared library to separate function

Minor cleanup in python interface

---

interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c

- fix `zlu_mem` declaration for multiphase with slacks
- multi phase template remove redundant lines with 'i_fun'

Multiphase slack fix

---

interfaces/acados_matlab_octave/generate_c_code_disc_dyn.m
interfaces/acados_matlab_octave/generate_c_code_implicit_ode.m
interfaces/acados_matlab_octave/generate_c_code_nonlinear_constr.m
interfaces/acados_matlab_octave/generate_c_code_nonlinear_least_squares.m
interfaces/acados_template/acados_template/casadi_function_generation.py

Not for MX for now due to https://github.com/casadi/casadi/issues/3703

Exploit symmetry when generating Hessians with CasADi SX

---

examples/acados_matlab_octave/control_rates/F8_crusader_model.m
examples/acados_matlab_octave/control_rates/README.md
examples/acados_matlab_octave/control_rates/main.m
examples/acados_matlab_octave/test/test_all_examples.m

This PR contributes an example with constraints and cost on the control input rates.
It is a slightly modified version of the code originally posted [here](https://discourse.acados.org/t/penalties-and-constraints-for-control-input-rates-via-augmented-states/1070/5).
Also, the script which can be used to test all examples automatically was updated with the recent fixes in `acados`.

MATLAB interface - control rates example

---

examples/acados_python/mocp_transition_example/main.py
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c
interfaces/acados_template/acados_template/utils.py

See https://discourse.acados.org/t/error-on-jbu-setting-is-not-clear/1611

Improve error messages on J matrices in Python

---

acados/ocp_nlp/Makefile
docs/installation/index.md
examples/acados_python/zoRO_example/diff_drive/diff_drive_utils.py
examples/acados_python/zoRO_example/diff_drive/main.py
interfaces/acados_template/acados_template/utils.py

Reported here: https://discourse.acados.org/t/a-compile-error-when-run-make-examples-c/1640
minor:
- improve plot in example
- do not warn about CasADi 3.6.5

Fix make build system adding DDP source, recommend CMake

---

acados/ocp_nlp/ocp_nlp_sqp.c
examples/acados_python/tests/reset_test.py
interfaces/acados_template/acados_template/acados_ocp_solver.py

This PR addresses an issue which caused the SQP solver to always return status 4, if it was returned once.
This was introduced in https://github.com/acados/acados/pull/1057
Added a test to check that the OCP solver can recover from such a situation.

Fix QP status issue

---

examples/acados_python/mocp_transition_example/main.py
interfaces/acados_template/acados_template/acados_multiphase_ocp.py
interfaces/acados_template/acados_template/c_templates_tera/CMakeLists.in.txt
interfaces/acados_template/acados_template/c_templates_tera/Makefile.in
interfaces/acados_template/acados_template/c_templates_tera/multi_CMakeLists.in.txt
interfaces/acados_template/acados_template/c_templates_tera/multi_Makefile.in

This PR adds the cmake build systems for the multi-phase OCP (MOCP) solver in preparation for MOCP solvers in MATLAB.

Cmake for multi-phase OCP solver 

---

acados/ocp_qp/ocp_qp_hpipm.c
acados/ocp_qp/ocp_qp_osqp.c
examples/acados_python/pendulum_on_cart/ocp/nonuniform_discretization_example.py

- use `OSQP_INFITY`
- comments on how to export QP for Gianluca
- improve example

Small improvements

---

acados/ocp_nlp/ocp_nlp_ddp.c
acados/ocp_nlp/ocp_nlp_reg_mirror.c
acados/ocp_nlp/ocp_nlp_sqp.c
examples/acados_matlab_octave/test/test_ocp_linear_mass_spring.m
examples/acados_python/tests/regularization_test.py
interfaces/CMakeLists.txt
interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/mex_solver.in.m

- SQP & DDP: move regularize before check_termination, such that we can get the QP at the stationary point that is actually solved, if we exit with success.
- MEX: add functions `dump_last_qp_to_json`, `qp_diagnostics`

Matlab QP conditioning

---

docs/conf.py
docs/requirements.txt

Dependabot was sending mails about known security vulnerabilities detected in the dependency Jinja2 Version < 3.1.4

Update docs build requirements

---

interfaces/acados_template/acados_template/acados_ocp_options.py

Minor docstring update for
* custom update
* regularization options

Minor documentation update

---

examples/acados_matlab_octave/getting_started/extensive_example_ocp.m
examples/acados_python/furuta_pendulum/integrator_experiment.py
interfaces/acados_matlab_octave/acados_ocp.m
interfaces/acados_matlab_octave/ocp_get.c

This PR fixes the getter for `qp_solver_cond_H` for partially condensed OCPs.

Matlab: Getter for condensed QP matrices

---

interfaces/acados_template/acados_template/acados_multiphase_ocp.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/utils.py

- add `json_file` property with defaults in class, as this is dumped to json.
- set `Tsim` in `make_consistent`
- formatting
- remove redundant check for terminal cost

Minor Python changes from aligning Matlab

---

docs/citing/index.md
docs/list_of_projects/index.md

- Preprint on: 'Multi-Phase Optimal Control Problems for Efficient Nonlinear Model Predictive Control with acados'
- Nonlinear MPC for Quadrotors in Close-Proximity Flight with Neural Network Downwash Prediction, shared in https://discourse.acados.org/t/acados-featured-work-collection/265/11

Add references to documentation

---

examples/acados_matlab_octave/control_rates/F8_crusader_model.m
examples/acados_matlab_octave/control_rates/main.m
examples/acados_matlab_octave/getting_started/new_minimal_example_ocp.m
examples/acados_matlab_octave/test/test_mhe_lorentz.m

* minor cleanup `new_minimal_example_ocp.m`
* fix in `test_mhe_lorentz.m`
* rewrite to new interface of the example `control_rates`

MATLAB: minor cleanup of examples, rewrite to new interface

---

examples/acados_matlab_octave/getting_started/extensive_example_ocp.m
interfaces/acados_matlab_octave/AcadosOcpSolver.m
interfaces/acados_matlab_octave/generate_c_code_nonlinear_constr.m

fix `qp_diagnostics` with keyword argument as added in #1188, corresponding changes got lost in #1193 and test functionality in example

Matlab: Fix `qp_diagnostics` for partially condensed QP

---

interfaces/acados_matlab_octave/acados_template_mex/+acados_template_mex/compile_ocp_shared_lib.m

see https://github.com/acados/acados/issues/1209

MALTAB: switch back to generated Make, keep using CMake on Octave

---

examples/acados_matlab_octave/control_rates/main.m
examples/acados_matlab_octave/getting_started/extensive_example_ocp.m
examples/acados_python/pendulum_on_cart/ocp/nonuniform_discretization_example.py
interfaces/acados_matlab_octave/AcadosOcpOptions.m
interfaces/acados_matlab_octave/acados_ocp_opts.m
interfaces/acados_matlab_octave/setup_AcadosOcp_from_legacy_ocp_description.m
interfaces/acados_template/acados_template/acados_ocp_options.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c

Plus: add setter to change the value interactively in MATLAB.

Add option `qp_solver_mu0` to `AcadosOcpOptions`

---

.github/linux/export_paths.sh
examples/acados_matlab_octave/mocp_transition_example/env.sh
examples/acados_matlab_octave/mocp_transition_example/formulate_double_integrator_ocp.m
examples/acados_matlab_octave/mocp_transition_example/formulate_single_integrator_ocp.m
examples/acados_matlab_octave/mocp_transition_example/get_double_integrator_model.m
examples/acados_matlab_octave/mocp_transition_example/get_example_settings.m
examples/acados_matlab_octave/mocp_transition_example/get_transition_model.m
examples/acados_matlab_octave/mocp_transition_example/main_multiphase_ocp.m
examples/acados_matlab_octave/mocp_transition_example/main_standard_ocp.m
examples/acados_matlab_octave/test/test_all_examples.m
interfaces/CMakeLists.txt
interfaces/acados_matlab_octave/AcadosModel.m
interfaces/acados_matlab_octave/AcadosMultiphaseOcp.m
interfaces/acados_matlab_octave/AcadosMultiphaseOptions.m
interfaces/acados_matlab_octave/AcadosOcp.m
interfaces/acados_matlab_octave/find_non_default_fields_of_obj.m
interfaces/acados_matlab_octave/generate_c_code_disc_dyn.m
interfaces/acados_matlab_octave/generate_c_code_discrete_dynamics.m
interfaces/acados_matlab_octave/ocp_get.c
interfaces/acados_matlab_octave/sim_generate_c_code.m
interfaces/acados_template/acados_template/acados_multiphase_ocp.py
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c

Simulink is not supported yet.

MATLAB multiphase OCP solver

---

docs/python_interface/py_acados_classes.dot
interfaces/acados_matlab_octave/AcadosSim.m
interfaces/acados_template/acados_template/__init__.py
interfaces/acados_template/acados_template/acados_sim.py
interfaces/acados_template/acados_template/acados_sim_solver.py

Closes https://github.com/acados/acados/issues/1220

Python: rename AcadosSimOpts -> AcadosSimOptions 

---

interfaces/acados_template/acados_template/c_templates_tera/CMakeLists.in.txt
interfaces/acados_template/acados_template/c_templates_tera/Makefile.in

Remove OCP related things in templated Make and CMake when creating integrators

---

acados/ocp_nlp/ocp_nlp_constraints_bgh.c
acados/ocp_nlp/ocp_nlp_constraints_bgh.h
acados/ocp_nlp/ocp_nlp_constraints_bgp.c
acados/ocp_nlp/ocp_nlp_constraints_bgp.h
acados/ocp_nlp/ocp_nlp_constraints_common.h
acados/ocp_nlp/ocp_nlp_cost_common.h
acados/ocp_nlp/ocp_nlp_cost_conl.c
acados/ocp_nlp/ocp_nlp_cost_conl.h
acados/ocp_nlp/ocp_nlp_cost_external.c
acados/ocp_nlp/ocp_nlp_cost_external.h
acados/ocp_nlp/ocp_nlp_cost_ls.c
acados/ocp_nlp/ocp_nlp_cost_ls.h
acados/ocp_nlp/ocp_nlp_cost_nls.c
acados/ocp_nlp/ocp_nlp_cost_nls.h
acados/ocp_nlp/ocp_nlp_dynamics_common.h
acados/ocp_nlp/ocp_nlp_dynamics_cont.c
acados/ocp_nlp/ocp_nlp_dynamics_cont.h
acados/ocp_nlp/ocp_nlp_dynamics_disc.c
acados/ocp_nlp/ocp_nlp_dynamics_disc.h
examples/c/no_interface_examples/mass_spring_nmpc_example.c
examples/c/no_interface_examples/nonlinear_chain_ocp_nlp_no_interface.c
interfaces/acados_c/ocp_nlp_interface.c

Useful for debugging and to implement new logic.

Add stage info in dynamics, cost and constraints submodules

---

interfaces/acados_template/acados_template/casadi_function_generation.py

Now that we have access to expressions, no need to take a detour.

Simplify casadi_function_generation logic

---

acados/ocp_nlp/ocp_nlp_sqp_rti.c

Fix check corresponding to #1254

Fix globalization status check in RTI

---

interfaces/acados_template/acados_template/c_templates_tera/main.in.c

Should have been done in #1260

Remove `rti_phase` in generated main file

---

examples/acados_matlab_octave/p_global_example/create_ocp_formulation_without_opts.m
examples/acados_matlab_octave/p_global_example/main.m
examples/acados_python/p_global_example/example_p_global.py
interfaces/acados_matlab_octave/AcadosModel.m
interfaces/acados_matlab_octave/AcadosMultiphaseOcp.m
interfaces/acados_matlab_octave/AcadosOcp.m
interfaces/acados_matlab_octave/AcadosSim.m
interfaces/acados_matlab_octave/acados_ocp_opts.m
interfaces/acados_matlab_octave/setup_AcadosOcp_from_legacy_ocp_description.m
interfaces/acados_template/acados_template/acados_multiphase_ocp.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h

Add field `p_global_values` to OCP object in MATLAB and python interface and initialize `p_global` with the provided values at solver creation.

Initialization of `p_global`

---

interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_matlab_octave/AcadosOcpSolver.m
interfaces/acados_matlab_octave/ocp_get.c
interfaces/acados_template/acados_template/acados_ocp_solver.py

- added `zl`, `zu`, `Zl`, `Zu`, `idxs`, `idxb`
- interfaced them in python and added `to dump_last_qp_to_json`
- in MATLAB getters for the integer fields are not implemented yet

Interfacing: Getters for QP data

---

acados/utils/external_function_generic.c
acados/utils/external_function_generic.h
interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

- remove unused `set*` functions
- rename variables to be more verbose

C: cleanup external function code

---

acados/sim/sim_gnsf.c
acados/sim/sim_irk_integrator.c
interfaces/acados_template/acados_template/acados_ocp_options.py

This PR separates functionality for computing z and algebraic sensitivities with the IRK and GNSF integrators. Note that algebraic variables are not supported for LIFTED_IRK.

Separate functionality for computing z and algebraic sensitivities

---

examples/acados_matlab_octave/generic_nlp/README.md
examples/acados_matlab_octave/generic_nlp/main.m
examples/acados_matlab_octave/test/test_all_examples.m

This PR suggests a new example on solving a non-OCP NLP using the MATLAB interface.
The original code was taken from [this post](https://discourse.acados.org/t/solving-simple-nlp-problem-exploit-blasfeo-performance/271).

MATLAB: generic NLP example

---

examples/acados_matlab_octave/p_global_example/main.m
interfaces/acados_matlab_octave/GenerateContext.m
interfaces/acados_template/acados_template/casadi_function_generation.py

reduce size of `global_data` by using previously extracted parametric expressions if possible

Optimize global data

---

Makefile
docs/installation/index.md

Closes https://github.com/acados/acados/issues/1318

Fix Make build system, add deprecation warning

---

interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx

Reported in https://github.com/acados/acados/issues/1113

Cython wrapper: fix import typing

---

docs/matlab_octave_interface/index.md
docs/python_interface/index.md
examples/acados_matlab_octave/getting_started/extensive_example_ocp.m
examples/acados_matlab_octave/getting_started/minimal_example_closed_loop.m
examples/acados_matlab_octave/test/test_all_examples.m
interfaces/acados_matlab_octave/AcadosOcp.m
interfaces/acados_matlab_octave/GenerateContext.m

This PR fixes a few small typos in the MATLAB examples and the website.

Minor cleanup

---

interfaces/acados_template/acados_template/c_templates_tera/constraints.in.h
interfaces/acados_template/acados_template/c_templates_tera/cost.in.h
interfaces/acados_template/acados_template/c_templates_tera/model.in.h

Should have happened in #1313 already

Templated headers: remove `get_pool_double`

---

examples/acados_python/rsm_example/main.py
interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_template/acados_template/acados_ocp_solver.py

This PR adds a flat setter and getter for stage-varying parameters `p`.

C interface, python: Flat setter and getter for stage-varying parameters `p`

---

.github/workflows/full_build.yml
examples/acados_matlab_octave/mocp_transition_example/formulate_double_integrator_ocp.m
examples/acados_matlab_octave/mocp_transition_example/formulate_single_integrator_ocp.m
examples/acados_matlab_octave/mocp_transition_example/main_parametric_mocp.m
examples/acados_matlab_octave/mocp_transition_example/main_standard_ocp.m
examples/acados_matlab_octave/test/run_matlab_examples_new_casadi.m
interfaces/acados_matlab_octave/AcadosMultiphaseOcp.m
interfaces/acados_matlab_octave/mex_macros.h
interfaces/acados_template/acados_template/acados_multiphase_ocp.py
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c
interfaces/acados_template/acados_template/c_templates_tera/multi_CMakeLists.in.txt

- MATLAB: fix zero default for `parameter_values` of MOCP
- fix `cost_0` in `multi_CMakeLists.in.txt `
- improve dimension check when setting parameters
- test MOCP with parameters in MATLAB

MOCP: fixes and test with parameters in MATLAB on CI

---

examples/acados_python/pendulum_on_cart/ocp/minimal_example_batch_ocp_solver.py
interfaces/acados_template/acados_template/acados_ocp_batch_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h

This PR extends the `AcadosOcpBatchSolver` with `set_flat`.

C template/python: `set_flat` for `AcadosOcpBatchSolver`

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_constraints_bgh.c
acados/ocp_nlp/ocp_nlp_constraints_bgh.h
acados/ocp_nlp/ocp_nlp_constraints_bgp.c
acados/ocp_nlp/ocp_nlp_constraints_bgp.h
acados/ocp_nlp/ocp_nlp_constraints_common.h
acados/utils/external_function_generic.c
examples/acados_python/pendulum_on_cart/solution_sensitivities/forw_vs_adj_param_sens.py
examples/acados_python/pendulum_on_cart/solution_sensitivities/policy_gradient_example.py
examples/acados_python/pendulum_on_cart/solution_sensitivities/sensitivity_utils.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.h
interfaces/acados_template/acados_template/c_templates_tera/constraints.in.h
interfaces/acados_template/acados_template/casadi_function_generation.py

This extends the existing functionality to handle constraints `h` that depend on `p_global`.
Limitations:
* Currently, only a linear dependence of `h` on `p_global` is supported.

Solution & value sensitivities with parametric constraints

---

acados/dense_qp/dense_qp_daqp.c

This PR update the DAQP submodule to address #1124

Update DAQP submodule

---

interfaces/acados_template/acados_template/acados_ocp_batch_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver.py

Cf. https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html

Python: avoid calling ascontiguousarray, improve docstings

---

acados/ocp_nlp/ocp_nlp_cost_ls.c
acados/ocp_nlp/ocp_nlp_cost_ls.h
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_batch_solver.py
interfaces/acados_template/acados_template/acados_ocp_solver.py

Plus:
- improve sanity checks for solution sensitivities in Python
- Simplify dimension setters in LS cost

Parametric sensitivities with linear least-squares cost

---

acados/ocp_nlp/ocp_nlp_ddp.c
acados/ocp_nlp/ocp_nlp_sqp_rti.c
interfaces/acados_template/acados_template/c_templates_tera/main.in.c

Was missing.
Plus, added test call for adjoint solution sensitivities in templated main for debugging.

Implement adjoint sensitivities for SQP-RTI and DDP

---

interfaces/acados_matlab_octave/AcadosOcp.m
interfaces/acados_matlab_octave/AcadosOcpOptions.m

* Remove redundant and broken check.
* Add missing funnel options.

Matlab: Fix funnel check and options

---

.github/linux/install_casadi_octave.sh
docs/matlab_octave_interface/index.md

Addresses issue reported in https://discourse.acados.org/t/beginner-octave-installation/1904/2

Update Octave installation instructions

---

examples/acados_python/convex_problem_globalization_needed/convex_problem_globalization_necessary.py

- test all cases
- add check
- simplify

Python: improve globalization test

---

examples/acados_matlab_octave/linear_mpc/main.m
examples/acados_matlab_octave/mocp_transition_example/formulate_single_integrator_ocp.m
interfaces/acados_matlab_octave/AcadosOcp.m

This PR adds a check for the indices related to simple bounds.

MATLAB: check values in `idxbx[_0,_e]` and `idxbu`

---

interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/mpc_utils.py

After using in on more complicated examples, I realized there were few bugs that I fixed here.
- Fixing a bug in raising warning for GN Hessian

Fix detect constraint for python interface

---

interfaces/acados_template/acados_template/acados_ocp_solver.py
interfaces/acados_template/acados_template/acados_sim_solver.py
interfaces/acados_template/acados_template/casadi_function_generation.py
interfaces/acados_template/acados_template/utils.py

Use `with` statement for temporarily changing the working directory.

Python: use context for temporarily changing directory

---

interfaces/acados_c/ocp_nlp_interface.c
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c

Use of more efficient flat getters/setters in Simulink S-function.

Simulink: More effiicient setters/getters using flat format

---

CONTRIBUTORS.txt
docs/list_of_projects/index.md
docs/python_interface/index.md
interfaces/acados_template/acados_template/acados_ocp_iterate.py

- Update contributor list
- document AcadosOcp iterate objects
-  update list of acados featured projects

Update documentation & contributor list

---

interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_solver_sfun.in.c

Fix number of outputs in S-function in edge cases, as reported in https://discourse.acados.org/t/error-on-the-s-function-block/1983/8

Simulink: compute n_outputs correctly, taking ifs into account

---

interfaces/acados_c/ocp_nlp_interface.c

Remove constraint dimensions from `ocp_nlp_cost_dims_get_from_attr`

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_ddp.c
acados/ocp_nlp/ocp_nlp_sqp.c
acados/ocp_nlp/ocp_nlp_sqp_rti.c
acados/ocp_qp/ocp_qp_xcond_solver.h
interfaces/acados_c/ocp_nlp_interface.h

Plus define struct `ocp_qp_xcond_solver`

C:  allow using differnt QP solvers in `ocp_nlp_solve_qp_and_correct_dual`

---

acados/dense_qp/dense_qp_common.h
acados/dense_qp/dense_qp_daqp.c
acados/dense_qp/dense_qp_hpipm.c
acados/dense_qp/dense_qp_ooqp.c
acados/dense_qp/dense_qp_qore.c
acados/dense_qp/dense_qp_qpoases.c
acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_qp/ocp_qp_common.h
acados/ocp_qp/ocp_qp_hpipm.c
acados/ocp_qp/ocp_qp_hpmpc.c
acados/ocp_qp/ocp_qp_ooqp.c
acados/ocp_qp/ocp_qp_osqp.c
acados/ocp_qp/ocp_qp_qpdunes.c
acados/ocp_qp/ocp_qp_xcond_solver.c
acados/ocp_qp/ocp_qp_xcond_solver.h

Follow-up to #1432
Addresses this comment https://github.com/acados/acados/pull/1432#issuecomment-2650612802

Options getter for QP solvers, backup opts in `setup_qp_matrices_and_factorize`

---

acados/ocp_nlp/ocp_nlp_sqp.c
interfaces/acados_template/acados_template/c_templates_tera/matlab_templates/acados_mex_set.in.c

Closes https://github.com/acados/acados/issues/1441

MATLAB: check when updating `nlp_solver_max_iter`

---

examples/acados_python/pendulum_on_cart/ocp/example_sqp_rti_loop.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/acados_ocp_constraints.py

- fix and test `remove_x0_elimination()`
- improve & simplify checks

Python: fixes regarding x0 constraint and sanity checks

---

acados/ocp_nlp/ocp_nlp_constraints_bgh.c
acados/ocp_nlp/ocp_nlp_constraints_bgp.c
examples/acados_python/chain_mass/export_chain_mass_model.py
examples/acados_python/chain_mass/export_disturbed_chain_mass_model.py
examples/acados_python/chain_mass/plot_utils.py
examples/acados_python/chain_mass/solution_sensitivity_example.py
examples/acados_python/pendulum_on_cart/solution_sensitivities/policy_gradient_example.py
examples/acados_python/pendulum_on_cart/solution_sensitivities/sensitivity_utils.py
examples/acados_python/pendulum_on_cart/solution_sensitivities/smooth_policy_gradients.py
examples/acados_python/solution_sensitivities_convex_example/non_ocp_example.py
interfaces/acados_template/acados_template/acados_ocp_solver.py

- Improve examples
- Add `smooth_policy_gradients.py`, OCP version similar to example added in https://github.com/acados/acados/pull/1439
- Add option to update `tau_min` in Python
- Add getter for number of equalities `ne` in constraint modules

Solution sensitivity examples

---

acados/ocp_nlp/ocp_nlp_common.c
acados/ocp_nlp/ocp_nlp_common.h
acados/ocp_nlp/ocp_nlp_sqp_with_feasible_qp.c
acados/ocp_nlp/ocp_nlp_sqp_with_feasible_qp.h
interfaces/acados_template/acados_template/acados_ocp_solver.py

`SQP_WITH_FEASIBLE_QP` prints multipliers `pi` and `lam` infinity norm now in output and in `print_statistics` in python

Logging and priniting of multipliers in `SQP_WITH_FEASIBLE_QP`

---

examples/acados_python/pendulum_on_cart/ocp/ocp_example_cost_formulations.py
interfaces/acados_template/acados_template/acados_ocp.py

This is in particularly useful when computing parametric solution sensitivities with a two-solver approach.
It allows to use the same parameterization of the problem in both solvers, but to use a Gauss-Newton Hessian in the "nominal" solver.
Note: for linear LS cost, there is nothing to do, as the exact Hessian and its GN approximation coincide.

Python: Implement reformulation as external cost with Gauss-Newton for LS/NLS

---

interfaces/acados_template/acados_template/mpc_utils.py

- fix get_path_cost_expression for `CONVEX_OVER_NONLINEAR`, broken in #1402
- fix also for terminal cost
- removed comments

Fix `get_path_cost_expression` for `CONVEX_OVER_NONLINEAR`

---

interfaces/acados_template/acados_template/acados_model.py

Finally `AcadosModel` with properties. 
Next step: move type checks from `make_consistent` to setters

Python: Model with properties

---

interfaces/acados_matlab_octave/check_acados_requirements.m

Forgot to push this commit in https://github.com/acados/acados/pull/1485

Update automatic CasADi matlab install

---

acados/ocp_nlp/ocp_nlp_sqp_rti.c
examples/acados_matlab_octave/pendulum_on_cart_model/closed_loop_as_rti.m
examples/acados_python/pendulum_on_cart/as_rti/as_rti_closed_loop_example.py

- fix AS-RTI, broken in #1254 
- add tests on closed loop simulation results

Fix globalization calls in AS-RTI

---

interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

Template: avoid openmp dependency when not batched

---

interfaces/acados_matlab_octave/AcadosOcp.m
interfaces/acados_template/acados_template/acados_model.py
interfaces/acados_template/acados_template/acados_ocp.py
interfaces/acados_template/acados_template/casadi_function_generation.py

Check whether CasADi expressions of terminal stage depend on `u` or `z` 
+ minor cleanup in `make_consistent` and code generation

Python/MATLAB: Check CasADi expressions of terminal stage

---

examples/acados_python/hock_schittkowsky/hs015_test.py
examples/acados_python/hock_schittkowsky/hs016_test.py

by using different `code_export_directory`

Fix Hock Schittkowsky test on actions

---

examples/acados_matlab_octave/getting_started/minimal_example_closed_loop.m
examples/acados_matlab_octave/getting_started/minimal_example_sim.m
interfaces/acados_matlab_octave/AcadosSimSolver.m

Analogous to the [Python version](https://github.com/acados/acados/blob/8ff3477761d5272b0e5735b97cf3fd821a1bd0b3/interfaces/acados_template/acados_template/acados_sim_solver.py#L241).
I added a comment in the `getting_started` examples, for new users.

MATLAB: implement `AcadosSimSolver.simulate()`

---

examples/acados_python/casadi_tests/test_casadi_constraint.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/acados_casadi_ocp_solver.py

- Try to extend support for general linear constraint, i.e. $lg<= Cx + Du <= ug$ in `g` of casadi solver
- add a ready test for testing constraint.

`AcadosCasadiOcp`: add support for general linear constraint

---

acados/ocp_qp/ocp_qp_common.c
examples/acados_python/furuta_pendulum/convergence_experiment.py
examples/acados_python/furuta_pendulum/furuta_common.py
examples/acados_python/furuta_pendulum/slack_eq_convergence_experiment.py
interfaces/acados_template/acados_template/acados_ocp_iterate.py

additionally:
- AcadosOcpFlattenedIterate: add __add__, __sub__, inf_norm

Investigate split variant of anderson acceleration for slacks

---

examples/acados_python/casadi_tests/test_casadi_slack_in_h.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/acados_casadi_ocp_solver.py

- Add support for soft nonlinear constraint in `AcadosCasadiOCP`
- Preliminarily complete `get()` and `set()`for slack variables in `AcadosCasadiOcpSolver`
- Add a draft test for testing soft nonlinear constraint
- Initially write some helper functions for simplification

`AcadosCasadiOCP`: Add support for soft nonlinear constraints

---

interfaces/acados_template/acados_template/c_templates_tera/acados_multi_solver.in.c
interfaces/acados_template/acados_template/c_templates_tera/acados_solver.in.c

- added `if (N > 0) in C template to fix solver warning: "exceeds maximum object size" see https://github.com/acados/acados/issues/1529
- minor fix in multi-phase

Template fixes

---

examples/acados_python/casadi_tests/test_casadi_LICQ_violation.py
interfaces/CMakeLists.txt
interfaces/acados_template/acados_template/acados_casadi_ocp_solver.py

- add function for checking strict complementarity in `AcadosCasadiOcpSolver`, not tested yet
- add function for checking LICQ in `AcadosCasadiOcpSolver`
- add test for validating check LICQ

`AcadosCasadiOcpSolver`: add support for checking LICQ

---

examples/acados_python/tests/pcond_getters_test.py
interfaces/acados_template/acados_template/acados_ocp_solver.py

- output full matrix for `pcond_Q`, `pcond_R`, before was just lower triagonal
- improve example

Partial condensing interface followup

---

docs/features/index.md
examples/acados_python/getting_started/minimal_example_closed_loop.py
examples/acados_python/getting_started/utils.py

Makes ``minimal_example_closed_loop.py`` more minimal.

Improve python minimal closed-loop example

---

examples/acados_python/zoRO_example/diff_drive/diff_drive_utils.py
examples/acados_python/zoRO_example/diff_drive/main.py
examples/acados_python/zoRO_example/diff_drive/mpc_parameters.py

dataclasses using default factories;
create all plots when calling main, show only at end;
cleaned dataclasses.

Update zoro example
